/*
	clean_contact.c

	Program to extract clean C source code from C file generated by Autolev program contact.al
	
*/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <time.h>
#include "mex.h"

#include "gait2d_osim_contact.h"
#define STRLEN 100 				// source lines are never longer than 100 characters

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {

	FILE *fid1, *fid2;
	char line[STRLEN];
	int i, copying;
	char *ptr;
    
    #if defined(WIN32) || defined(_WIN32) || defined(__WIN32) && !defined(__CYGWIN__)
    char *slash="\\";
    #else
    char *slash="/";
    #endif

// open the file that came from Autolev
	printf("Cleaning Autolev output from contact.al...\n");

// open the file that came from Autolev
    char filename1[100];
    strcpy(filename1, "contact");
    strcat(filename1, slash);
    strcat(filename1, "contact_2d_raw.c");
	if ((fid1 = fopen(filename1,"r")) == NULL) {
		printf("Could not open %s\n", filename1);
		exit(1);
	}
	
// write the clean C file
    char filename2[100];
    strcpy(filename2, "contact");
    strcat(filename2, slash);
    strcat(filename2, "contact_2d_al.c");
	if ((fid2 = fopen(filename2,"w")) == NULL) {
		printf("Could not write %s\n", filename2);
		exit(1);
	}
	fprintf(fid2,"// This file was generated by autolevclean2.c and contains C code generated by Autolev\n\n");
	fprintf(fid2,"#include <math.h>\n");
	fprintf(fid2,"#include \"gait2d_osim_contact.h\"\n");
	fprintf(fid2,"void contact_al(contactprop* contact,\n");										
	fprintf(fid2,"\tdouble fk[6], double fkdot[6], double x[NCVAR], double xdot[NCVAR],\n");			
	fprintf(fid2,"\tdouble f[NCF], double df_dfk[NCF][6], double df_dfkdot[NCF][6],\n");
	fprintf(fid2,"\tdouble df_dx[NCF][NCVAR], double df_dxdot[NCF][NCVAR]) {\n\n");		
	
	// generate C code to copy input arrays into scalar variables
	for (i=0; i<6; i++) {
		fprintf(fid2,"\tdouble fk%1d = fk[%1d];\n", i+1,i);		
		fprintf(fid2,"\tdouble fkdot%1d = fkdot[%1d];\n", i+1,i);	
	}
	for (i=0; i<NCVAR; i++) {
		fprintf(fid2,"\tdouble x%1d = x[%1d];\n", i+1,i);	
        fprintf(fid2,"\tdouble xdot%1d = xdot[%1d];\n", i+1,i);		
	}

	// declare the temporary variables
	fprintf(fid2,"\tdouble Ffric,v;\n");
	fprintf(fid2,"\tdouble dx,dy,dxf,dyf;\n");
	fprintf(fid2,"\tdouble xc, yc, xcdot, ycdot, Fx, Fy;\n");
	fprintf(fid2,"\tdouble xf, yf, xcloc, ycloc;\n");
	fprintf(fid2,"\tdouble Fxloc, Fyloc, d, ddot, Fmag;\n");
	fprintf(fid2,"\tdouble dfx, dfy;\n");
	for (i=0; i<NCF; i++) {
		fprintf(fid2,"\tdouble f%d, ff%d;\n", i+1, i+1);		
	}
		
	// copy the necessary parts of C code from fid1 to fid2
	copying = 0;
	while (feof(fid1) == 0) {
		fgets(line, STRLEN, fid1);
		if (strncmp(line, "double   Pi,DEGtoRAD,RADtoDEG,z[", 32) == 0) {
			fprintf(fid2,"\tstatic double z[%d];\n",atoi(&line[32]));		// make sure there is enough room for all Zs
		}
		if ((strcmp(line, "/* Evaluate constants */\n") == 0) || (strcmp(line, "/* Evaluate constants */\r\n") == 0))				// Z[] code starts here
			copying = 1;
		else if ((strcmp(line, "/* Evaluate output quantities */\n") == 0) || (strcmp(line, "/* Evaluate output quantities */\r\n") == 0))	// Z[] code ends here
			copying = 0;
		else if ((strcmp(line, "/* Write output to screen and to output file(s) */\n") == 0) || (strcmp(line, "/* Write output to screen and to output file(s) */\r\n") == 0))		// kinematics code starts here
			copying = 1;
		else if ((strcmp(line, "  Encode[0] = 0.0;\n") == 0) || (strcmp(line, "  Encode[0] = 0.0;\r\n") == 0))	// and stop here
			copying = 0;
		else if (copying) {
			// convert contact__ into contact->
			ptr = strstr(line, "contact__");
			while (ptr != NULL) {
				strncpy(ptr, "contact->", 9);
				ptr = strstr(line, "contact__");
			}
			fputs(line, fid2);
		}
	}
	
	// close the input file
	fclose(fid1);
	
	// close the output file
	fprintf(fid2,"}\n");
	fclose(fid2);
		
}			// END OF MAIN PROGRAM
