// This file was generated by autolevclean2.c and contains C code generated by Autolev

#include <math.h>
#include "gait2dc.h"
void contact_al(contactprop* contact,
	double fk[6], double fkdot[6], double xc[4], double xcdot[2],
	double f[4], double df_dfk[4][6], double df_dfkdot[4][6],
	double df_dxc[4][4], double df_dxcdot[4][2]) {

	double fk1 = fk[0];
	double fkdot1 = fkdot[0];
	double fk2 = fk[1];
	double fkdot2 = fkdot[1];
	double fk3 = fk[2];
	double fkdot3 = fkdot[2];
	double fk4 = fk[3];
	double fkdot4 = fkdot[3];
	double fk5 = fk[4];
	double fkdot5 = fkdot[4];
	double fk6 = fk[5];
	double fkdot6 = fkdot[5];
	double xc1 = xc[0];
	double xc2 = xc[1];
	double xc3 = xc[2];
	double xc4 = xc[3];
	double xcdot1 = xcdot[0];
	double xcdot2 = xcdot[1];
	double d,d1,d2,sd1,sd2,Ffriction,Fnormal;
	static double z[34];
  d1 = contact->c*xc4*(-1+10*xcdot1) - xc3;
  d2 = contact->c*xc4*(1+10*xcdot1) - xc3;
  sd1 = pow((contact->LambdaX+pow(d1,2)),0.5);
  sd2 = pow((contact->LambdaX+pow(d2,2)),0.5);
  Ffriction = sd1 - 2*xc3 - sd2;
  d = pow((contact->LambdaY+pow(xc4,2)+40000*pow(xc2,2)),0.5);
  Fnormal = xc4 + 200*xc2 - d;
  z[1] = fk3*xc3 + fk5*xc4 + contact->kxx*(contact->x+fk3*(fk1-xc1)+fk5*(fk2-
  xc2)) + contact->kxy*(contact->y+fk4*(fk1-xc1)+fk6*(fk2-xc2)) + contact->b*(
  fk3*(fkdot1-xcdot1)+fk5*(fkdot2-xcdot2)+fkdot3*(fk1-xc1)+fkdot5*(fk2-xc2));
  z[2] = fk4*xc3 + fk6*xc4 + contact->kxy*(contact->x+fk3*(fk1-xc1)+fk5*(fk2-
  xc2)) + contact->kyy*(contact->y+fk4*(fk1-xc1)+fk6*(fk2-xc2)) + contact->b*(
  fk4*(fkdot1-xcdot1)+fk6*(fkdot2-xcdot2)+fkdot4*(fk1-xc1)+fkdot6*(fk2-xc2));
  z[3] = contact->b*fkdot3 + contact->kxx*fk3 + contact->kxy*fk4;
  z[4] = contact->b*fkdot5 + contact->kxx*fk5 + contact->kxy*fk6;
  z[5] = xc3 + contact->b*(fkdot1-xcdot1) + contact->kxx*(fk1-xc1);
  z[6] = xc4 + contact->b*(fkdot2-xcdot2) + contact->kxx*(fk2-xc2);
  z[7] = contact->b*fkdot4 + contact->kxy*fk3 + contact->kyy*fk4;
  z[8] = contact->b*fkdot6 + contact->kxy*fk5 + contact->kyy*fk6;
  z[9] = xc3 + contact->b*(fkdot1-xcdot1) + contact->kyy*(fk1-xc1);
  z[10] = xc4 + contact->b*(fkdot2-xcdot2) + contact->kyy*(fk2-xc2);
  z[11] = contact->kxy*(fk1-xc1);
  z[12] = contact->kxy*(fk2-xc2);
  z[13] = contact->b*fk3;
  z[14] = contact->b*fk5;
  z[15] = contact->b*(fk1-xc1);
  z[16] = contact->b*(fk2-xc2);
  z[17] = contact->b*fk4;
  z[18] = contact->b*fk6;
  z[19] = -2 + d2/pow((contact->LambdaX+pow(d2,2)),0.5) - d1/pow((contact->LambdaX+
  pow(d1,2)),0.5);
  z[20] = contact->c*d1*(-1+10*xcdot1)/pow((contact->LambdaX+pow(d1,2)),0.5);
  z[21] = contact->c*d2*(1+10*xcdot1)/pow((contact->LambdaX+pow(d2,2)),0.5);
  z[22] = xc2/pow((contact->LambdaY+pow(xc4,2)+40000*pow(xc2,2)),0.5);
  z[23] = xc4/pow((contact->LambdaY+pow(xc4,2)+40000*pow(xc2,2)),0.5);
  z[24] = -contact->b*fkdot3 - contact->kxx*fk3 - contact->kxy*fk4;
  z[25] = -contact->b*fkdot5 - contact->kxx*fk5 - contact->kxy*fk6;
  z[26] = -contact->b*fkdot4 - contact->kxy*fk3 - contact->kyy*fk4;
  z[27] = -contact->b*fkdot6 - contact->kxy*fk5 - contact->kyy*fk6;
  z[28] = z[20] - z[21];
  z[29] = 200 - 40000*z[22];
  z[30] = 1 - z[23];
  z[31] = contact->c*d1*xc4/pow((contact->LambdaX+pow(d1,2)),0.5);
  z[32] = contact->c*d2*xc4/pow((contact->LambdaX+pow(d2,2)),0.5);
  z[33] = 10*z[31] - 10*z[32];


  f[0] = Ffriction;
  f[1] = Fnormal;
  f[2] = z[1];
  f[3] = z[2];
  df_dfk[0][0] = 0;
  df_dfk[0][1] = 0;
  df_dfk[0][2] = 0;
  df_dfk[0][3] = 0;
  df_dfk[0][4] = 0;
  df_dfk[0][5] = 0;
  df_dfk[1][0] = 0;
  df_dfk[1][1] = 0;
  df_dfk[1][2] = 0;
  df_dfk[1][3] = 0;
  df_dfk[1][4] = 0;
  df_dfk[1][5] = 0;
  df_dfk[2][0] = z[3];
  df_dfk[2][1] = z[4];
  df_dfk[2][2] = z[5];
  df_dfk[2][3] = z[11];
  df_dfk[2][4] = z[6];
  df_dfk[2][5] = z[12];
  df_dfk[3][0] = z[7];
  df_dfk[3][1] = z[8];
  df_dfk[3][2] = z[11];
  df_dfk[3][3] = z[9];
  df_dfk[3][4] = z[12];
  df_dfk[3][5] = z[10];
  df_dfkdot[0][0] = 0;
  df_dfkdot[0][1] = 0;
  df_dfkdot[0][2] = 0;
  df_dfkdot[0][3] = 0;
  df_dfkdot[0][4] = 0;
  df_dfkdot[0][5] = 0;
  df_dfkdot[1][0] = 0;
  df_dfkdot[1][1] = 0;
  df_dfkdot[1][2] = 0;
  df_dfkdot[1][3] = 0;
  df_dfkdot[1][4] = 0;
  df_dfkdot[1][5] = 0;
  df_dfkdot[2][0] = z[13];
  df_dfkdot[2][1] = z[14];
  df_dfkdot[2][2] = z[15];
  df_dfkdot[2][3] = 0;
  df_dfkdot[2][4] = z[16];
  df_dfkdot[2][5] = 0;
  df_dfkdot[3][0] = z[17];
  df_dfkdot[3][1] = z[18];
  df_dfkdot[3][2] = 0;
  df_dfkdot[3][3] = z[15];
  df_dfkdot[3][4] = 0;
  df_dfkdot[3][5] = z[16];
  df_dxc[0][0] = 0;
  df_dxc[0][1] = 0;
  df_dxc[0][2] = z[19];
  df_dxc[0][3] = z[28];
  df_dxc[1][0] = 0;
  df_dxc[1][1] = z[29];
  df_dxc[1][2] = 0;
  df_dxc[1][3] = z[30];
  df_dxc[2][0] = z[24];
  df_dxc[2][1] = z[25];
  df_dxc[2][2] = fk3;
  df_dxc[2][3] = fk5;
  df_dxc[3][0] = z[26];
  df_dxc[3][1] = z[27];
  df_dxc[3][2] = fk4;
  df_dxc[3][3] = fk6;
  df_dxcdot[0][0] = z[33];
  df_dxcdot[0][1] = 0;
  df_dxcdot[1][0] = 0;
  df_dxcdot[1][1] = 0;
  df_dxcdot[2][0] = -z[13];
  df_dxcdot[2][1] = -z[14];
  df_dxcdot[3][0] = -z[17];
  df_dxcdot[3][1] = -z[18];

}
