// This file was generated by autolevclean.c and contains C code generated by Autolev

#include <math.h>
#include "gait2dc.h"
void gait2dc_dynamics_al(param_struct* par, double q[NDOF], double qd[NDOF], double qdd[NDOF],
   double mom[NMOM], double grf[NGRF], double Zero[NDOF], double dz_dq[NDOF][NDOF],
   double dz_dqd[NDOF][NDOF], double dz_dqdd[NDOF][NDOF],
   double dz_dmom[NDOF][NMOM], double dz_dgrf[NDOF][NGRF],
   double fk[NFK], double dfk_dq[NFK][NDOF],
   double fkdot[NFK], double dfkdot_dq[NFK][NDOF]) {
	double q1 = q[0];
	double q1p = qd[0];
	double q1pp = qdd[0];
	double q2 = q[1];
	double q2p = qd[1];
	double q2pp = qdd[1];
	double q3 = q[2];
	double q3p = qd[2];
	double q3pp = qdd[2];
	double q4 = q[3];
	double q4p = qd[3];
	double q4pp = qdd[3];
	double q5 = q[4];
	double q5p = qd[4];
	double q5pp = qdd[4];
	double q6 = q[5];
	double q6p = qd[5];
	double q6pp = qdd[5];
	double q7 = q[6];
	double q7p = qd[6];
	double q7pp = qdd[6];
	double q8 = q[7];
	double q8p = qd[7];
	double q8pp = qdd[7];
	double q9 = q[8];
	double q9p = qd[8];
	double q9pp = qdd[8];
	double mom1 = mom[0];
	double mom2 = mom[1];
	double mom3 = mom[2];
	double mom4 = mom[3];
	double mom5 = mom[4];
	double mom6 = mom[5];
	double RFootFx = grf[0];
	double RFootFy = grf[1];
	double RFootMz = grf[2];
	double LFootFx = grf[3];
	double LFootFy = grf[4];
	double LFootMz = grf[5];
	static double z[619];
  z[1] = cos(q3);
  z[2] = sin(q3);
  z[3] = cos(q4);
  z[4] = sin(q4);
  z[5] = cos(q5);
  z[6] = sin(q5);
  z[7] = z[1]*z[3] - z[2]*z[4];
  z[8] = -z[1]*z[4] - z[2]*z[3];
  z[9] = z[1]*z[4] + z[2]*z[3];
  z[10] = q3p + q4p;
  z[11] = par->ThighLen*(q3p+q4p)*z[10];
  z[12] = cos(q6);
  z[13] = sin(q6);
  z[14] = z[5]*z[9] + z[6]*z[7];
  z[15] = z[5]*z[7] + z[6]*z[8];
  z[16] = par->ThighLen*z[5];
  z[17] = z[5]*z[7] - z[6]*z[9];
  z[18] = z[5]*z[8] - z[6]*z[7];
  z[19] = par->ThighLen*z[6];
  z[20] = par->ShankLen + z[16];
  z[21] = z[6]*z[11];
  z[22] = z[5]*z[11];
  z[23] = q3p + q4p + q5p;
  z[24] = z[22] + par->ShankLen*(q3p+q4p+q5p)*z[23];
  z[25] = cos(q7);
  z[26] = sin(q7);
  z[27] = cos(q8);
  z[28] = sin(q8);
  z[29] = z[1]*z[25] - z[2]*z[26];
  z[30] = -z[1]*z[26] - z[2]*z[25];
  z[31] = z[1]*z[26] + z[2]*z[25];
  z[32] = q3p + q7p;
  z[33] = par->ThighLen*(q3p+q7p)*z[32];
  z[34] = cos(q9);
  z[35] = sin(q9);
  z[36] = z[27]*z[31] + z[28]*z[29];
  z[37] = z[27]*z[29] + z[28]*z[30];
  z[38] = par->ThighLen*z[27];
  z[39] = z[27]*z[29] - z[28]*z[31];
  z[40] = z[27]*z[30] - z[28]*z[29];
  z[41] = par->ThighLen*z[28];
  z[42] = par->ShankLen + z[38];
  z[43] = z[28]*z[33];
  z[44] = z[27]*z[33];
  z[45] = q3p + q7p + q8p;
  z[46] = z[44] + par->ShankLen*(q3p+q7p+q8p)*z[45];
  z[47] = z[12]*z[15] + z[13]*z[18];
  z[48] = z[12]*z[18] - z[13]*z[15];
  z[49] = z[12]*z[14] + z[13]*z[17];
  z[50] = z[12]*z[17] - z[13]*z[14];
  z[51] = z[34]*z[37] + z[35]*z[40];
  z[52] = z[34]*z[40] - z[35]*z[37];
  z[53] = z[34]*z[36] + z[35]*z[39];
  z[54] = z[34]*z[39] - z[35]*z[36];
  z[55] = z[2]*z[4] - z[1]*z[3];
  z[56] = z[5]*z[8] + z[6]*z[55];
  z[57] = z[5]*z[55] - z[6]*z[8];
  z[58] = -z[5]*z[7] - z[6]*z[8];
  z[59] = -z[5]*z[9] - z[6]*z[7];
  z[60] = z[12]*z[56] + z[13]*z[57];
  z[61] = z[12]*z[18] + z[13]*z[58];
  z[62] = z[12]*z[57] - z[13]*z[56];
  z[63] = z[12]*z[58] - z[13]*z[18];
  z[64] = -z[12]*z[15] - z[13]*z[18];
  z[65] = z[12]*z[17] + z[13]*z[59];
  z[66] = z[12]*z[59] - z[13]*z[17];
  z[67] = -z[12]*z[14] - z[13]*z[17];
  z[68] = z[2]*z[26] - z[1]*z[25];
  z[69] = z[27]*z[30] + z[28]*z[68];
  z[70] = z[27]*z[68] - z[28]*z[30];
  z[71] = -z[27]*z[29] - z[28]*z[30];
  z[72] = -z[27]*z[31] - z[28]*z[29];
  z[73] = z[34]*z[69] + z[35]*z[70];
  z[74] = z[34]*z[40] + z[35]*z[71];
  z[75] = z[34]*z[70] - z[35]*z[69];
  z[76] = z[34]*z[71] - z[35]*z[40];
  z[77] = -z[34]*z[37] - z[35]*z[40];
  z[78] = z[34]*z[39] + z[35]*z[72];
  z[79] = z[34]*z[72] - z[35]*z[39];
  z[80] = -z[34]*z[36] - z[35]*z[39];
  z[81] = par->ThighLen*z[55];
  z[82] = par->ThighLen*z[8];
  z[83] = -par->ShankLen*z[57] - par->ThighLen*z[55];
  z[84] = par->ShankLen*z[58];
  z[85] = -par->ShankLen*z[18] - par->ThighLen*z[8];
  z[86] = par->ShankLen*z[59];
  z[87] = par->ThighLen*z[68];
  z[88] = par->ThighLen*z[30];
  z[89] = -par->ShankLen*z[70] - par->ThighLen*z[68];
  z[90] = par->ShankLen*z[71];
  z[91] = -par->ShankLen*z[40] - par->ThighLen*z[30];
  z[92] = par->ShankLen*z[72];
  z[93] = z[2]*q3p;
  z[94] = z[1]*q3p;
  z[95] = z[8]*(q3p+q4p);
  z[96] = z[55]*(q3p+q4p);
  z[97] = z[7]*(q3p+q4p);
  z[98] = q1p - par->ThighLen*z[55]*(q3p+q4p);
  z[99] = q2p - par->ThighLen*z[8]*(q3p+q4p);
  z[100] = z[18]*q5p + z[56]*q3p + z[56]*q4p;
  z[101] = z[57]*q3p + z[57]*q4p + z[58]*q5p;
  z[102] = z[15]*q3p + z[15]*q4p + z[17]*q5p;
  z[103] = z[18]*q3p + z[18]*q4p + z[59]*q5p;
  z[104] = q1p - par->ThighLen*z[55]*(q3p+q4p) - par->ShankLen*(z[57]*q3p+
  z[57]*q4p+z[58]*q5p);
  z[105] = q2p - par->ThighLen*z[8]*(q3p+q4p) - par->ShankLen*(z[18]*q3p+
  z[18]*q4p+z[59]*q5p);
  z[106] = z[48]*q6p + z[60]*q3p + z[60]*q4p + z[61]*q5p;
  z[107] = z[62]*q3p + z[62]*q4p + z[63]*q5p + z[64]*q6p;
  z[108] = z[47]*q3p + z[47]*q4p + z[50]*q6p + z[65]*q5p;
  z[109] = z[48]*q3p + z[48]*q4p + z[66]*q5p + z[67]*q6p;
  z[110] = z[30]*(q3p+q7p);
  z[111] = z[68]*(q3p+q7p);
  z[112] = z[29]*(q3p+q7p);
  z[113] = q1p - par->ThighLen*z[68]*(q3p+q7p);
  z[114] = q2p - par->ThighLen*z[30]*(q3p+q7p);
  z[115] = z[40]*q8p + z[69]*q3p + z[69]*q7p;
  z[116] = z[70]*q3p + z[70]*q7p + z[71]*q8p;
  z[117] = z[37]*q3p + z[37]*q7p + z[39]*q8p;
  z[118] = z[40]*q3p + z[40]*q7p + z[72]*q8p;
  z[119] = q1p - par->ThighLen*z[68]*(q3p+q7p) - par->ShankLen*(z[70]*q3p+
  z[70]*q7p+z[71]*q8p);
  z[120] = q2p - par->ThighLen*z[30]*(q3p+q7p) - par->ShankLen*(z[40]*q3p+
  z[40]*q7p+z[72]*q8p);
  z[121] = z[52]*q9p + z[73]*q3p + z[73]*q7p + z[74]*q8p;
  z[122] = z[75]*q3p + z[75]*q7p + z[76]*q8p + z[77]*q9p;
  z[123] = z[51]*q3p + z[51]*q7p + z[54]*q9p + z[78]*q8p;
  z[124] = z[52]*q3p + z[52]*q7p + z[79]*q8p + z[80]*q9p;
  z[125] = par->ThighLen*z[9]*(q3p+q4p);
  z[126] = par->ThighLen*z[55]*(q3p+q4p);
  z[127] = z[5]*z[55] + z[6]*z[9];
  z[128] = z[57]*q5p + z[127]*q3p + z[127]*q4p;
  z[129] = z[5]*z[9] - z[6]*z[55];
  z[130] = -z[5]*z[8] - z[6]*z[55];
  z[131] = z[129]*q3p + z[129]*q4p + z[130]*q5p;
  z[132] = z[6]*z[7] - z[5]*z[8];
  z[133] = z[130]*q3p + z[130]*q4p + z[132]*q5p;
  z[134] = z[6]*z[9] - z[5]*z[7];
  z[135] = z[58]*q3p + z[58]*q4p + z[134]*q5p;
  z[136] = -par->ThighLen*z[9]*(q3p+q4p) - par->ShankLen*(z[129]*q3p+z[129]*
  q4p+z[130]*q5p);
  z[137] = par->ShankLen*(z[130]*q3p+z[130]*q4p+z[132]*q5p);
  z[138] = -par->ThighLen*z[55]*(q3p+q4p) - par->ShankLen*(z[57]*q3p+z[57]*
  q4p+z[58]*q5p);
  z[139] = par->ShankLen*(z[58]*q3p+z[58]*q4p+z[134]*q5p);
  z[140] = z[12]*z[127] + z[13]*z[129];
  z[141] = z[12]*z[57] + z[13]*z[130];
  z[142] = z[62]*q6p + z[140]*q3p + z[140]*q4p + z[141]*q5p;
  z[143] = z[12]*z[58] + z[13]*z[132];
  z[144] = z[63]*q6p + z[141]*q3p + z[141]*q4p + z[143]*q5p;
  z[145] = z[12]*z[129] - z[13]*z[127];
  z[146] = z[12]*z[130] - z[13]*z[57];
  z[147] = -z[12]*z[56] - z[13]*z[57];
  z[148] = z[145]*q3p + z[145]*q4p + z[146]*q5p + z[147]*q6p;
  z[149] = z[12]*z[132] - z[13]*z[58];
  z[150] = -z[12]*z[18] - z[13]*z[58];
  z[151] = z[146]*q3p + z[146]*q4p + z[149]*q5p + z[150]*q6p;
  z[152] = z[13]*z[15] - z[12]*z[18];
  z[153] = z[147]*q3p + z[147]*q4p + z[150]*q5p + z[152]*q6p;
  z[154] = z[12]*z[59] + z[13]*z[134];
  z[155] = z[61]*q3p + z[61]*q4p + z[66]*q6p + z[154]*q5p;
  z[156] = z[12]*z[134] - z[13]*z[59];
  z[157] = -z[12]*z[17] - z[13]*z[59];
  z[158] = z[63]*q3p + z[63]*q4p + z[156]*q5p + z[157]*q6p;
  z[159] = z[13]*z[14] - z[12]*z[17];
  z[160] = z[64]*q3p + z[64]*q4p + z[157]*q5p + z[159]*q6p;
  z[161] = par->ThighLen*z[31]*(q3p+q7p);
  z[162] = par->ThighLen*z[68]*(q3p+q7p);
  z[163] = z[27]*z[68] + z[28]*z[31];
  z[164] = z[70]*q8p + z[163]*q3p + z[163]*q7p;
  z[165] = z[27]*z[31] - z[28]*z[68];
  z[166] = -z[27]*z[30] - z[28]*z[68];
  z[167] = z[165]*q3p + z[165]*q7p + z[166]*q8p;
  z[168] = z[28]*z[29] - z[27]*z[30];
  z[169] = z[166]*q3p + z[166]*q7p + z[168]*q8p;
  z[170] = z[28]*z[31] - z[27]*z[29];
  z[171] = z[71]*q3p + z[71]*q7p + z[170]*q8p;
  z[172] = -par->ThighLen*z[31]*(q3p+q7p) - par->ShankLen*(z[165]*q3p+z[165]*
  q7p+z[166]*q8p);
  z[173] = par->ShankLen*(z[166]*q3p+z[166]*q7p+z[168]*q8p);
  z[174] = -par->ThighLen*z[68]*(q3p+q7p) - par->ShankLen*(z[70]*q3p+z[70]*
  q7p+z[71]*q8p);
  z[175] = par->ShankLen*(z[71]*q3p+z[71]*q7p+z[170]*q8p);
  z[176] = z[34]*z[163] + z[35]*z[165];
  z[177] = z[34]*z[70] + z[35]*z[166];
  z[178] = z[75]*q9p + z[176]*q3p + z[176]*q7p + z[177]*q8p;
  z[179] = z[34]*z[71] + z[35]*z[168];
  z[180] = z[76]*q9p + z[177]*q3p + z[177]*q7p + z[179]*q8p;
  z[181] = z[34]*z[165] - z[35]*z[163];
  z[182] = z[34]*z[166] - z[35]*z[70];
  z[183] = -z[34]*z[69] - z[35]*z[70];
  z[184] = z[181]*q3p + z[181]*q7p + z[182]*q8p + z[183]*q9p;
  z[185] = z[34]*z[168] - z[35]*z[71];
  z[186] = -z[34]*z[40] - z[35]*z[71];
  z[187] = z[182]*q3p + z[182]*q7p + z[185]*q8p + z[186]*q9p;
  z[188] = z[35]*z[37] - z[34]*z[40];
  z[189] = z[183]*q3p + z[183]*q7p + z[186]*q8p + z[188]*q9p;
  z[190] = z[34]*z[72] + z[35]*z[170];
  z[191] = z[74]*q3p + z[74]*q7p + z[79]*q9p + z[190]*q8p;
  z[192] = z[34]*z[170] - z[35]*z[72];
  z[193] = -z[34]*z[39] - z[35]*z[72];
  z[194] = z[76]*q3p + z[76]*q7p + z[192]*q8p + z[193]*q9p;
  z[195] = z[35]*z[36] - z[34]*z[39];
  z[196] = z[77]*q3p + z[77]*q7p + z[193]*q8p + z[195]*q9p;
  z[197] = z[9]*(q3p+q4p);
  z[198] = z[31]*(q3p+q7p);
  z[199] = par->TrunkCMy*pow(q3p,2);
  z[200] = par->ThighCMy*(q3p+q4p)*z[10];
  z[201] = z[16] - par->ShankCMy;
  z[202] = z[22] - par->ShankCMy*(q3p+q4p+q5p)*z[23];
  z[203] = par->ShankLen*z[12];
  z[204] = z[12]*z[20] - z[13]*z[19];
  z[205] = -z[12]*z[19] - z[13]*z[20];
  z[206] = par->ShankLen*z[13];
  z[207] = z[203] - par->FootCMy;
  z[208] = z[204] - par->FootCMy;
  z[209] = par->FootCMx + z[205];
  z[210] = par->FootCMx - z[206];
  z[211] = z[12]*z[21] + z[13]*z[24];
  z[212] = z[12]*z[24] - z[13]*z[21];
  z[213] = q3p + q4p + q5p + q6p;
  z[214] = z[211] - par->FootCMx*(q3p+q4p+q5p+q6p)*z[213];
  z[215] = z[212] - par->FootCMy*(q3p+q4p+q5p+q6p)*z[213];
  z[216] = par->ThighCMy*(q3p+q7p)*z[32];
  z[217] = z[38] - par->ShankCMy;
  z[218] = z[44] - par->ShankCMy*(q3p+q7p+q8p)*z[45];
  z[219] = par->ShankLen*z[34];
  z[220] = z[34]*z[42] - z[35]*z[41];
  z[221] = -z[34]*z[41] - z[35]*z[42];
  z[222] = par->ShankLen*z[35];
  z[223] = z[219] - par->FootCMy;
  z[224] = z[220] - par->FootCMy;
  z[225] = par->FootCMx + z[221];
  z[226] = par->FootCMx - z[222];
  z[227] = z[34]*z[43] + z[35]*z[46];
  z[228] = z[34]*z[46] - z[35]*z[43];
  z[229] = q3p + q7p + q8p + q9p;
  z[230] = z[227] - par->FootCMx*(q3p+q7p+q8p+q9p)*z[229];
  z[231] = z[228] - par->FootCMy*(q3p+q7p+q8p+q9p)*z[229];
  z[232] = sin(par->slope);
  z[233] = par->FootMass*par->gravity*z[232];
  z[234] = cos(par->slope);
  z[235] = par->FootMass*par->gravity*z[234];
  z[236] = par->gravity*par->ShankMass*z[232];
  z[237] = par->gravity*par->ShankMass*z[234];
  z[238] = par->gravity*par->ThighMass*z[232];
  z[239] = par->gravity*par->ThighMass*z[234];
  z[240] = par->gravity*par->TrunkMass*z[232];
  z[241] = par->gravity*par->TrunkMass*z[234];
  z[242] = z[1]*q1p + z[2]*q2p - par->TrunkCMy*q3p;
  z[243] = z[1]*q2p - z[2]*q1p;
  z[244] = par->airdrag*par->wind;
  z[245] = pow(par->wind,2);
  z[246] = z[244]*pow((z[245]+pow(z[242],2)+pow(z[243],2)+2*par->wind*z[2]*
  z[243]-2*par->wind*z[1]*z[242]),0.5);
  z[247] = par->airdrag*(par->TrunkCMy*q3p-z[1]*q1p-z[2]*q2p)*pow((z[245]+
  pow(z[242],2)+pow(z[243],2)+2*par->wind*z[2]*z[243]-2*par->wind*z[1]*z[242]),
  0.5);
  z[248] = par->airdrag*(z[1]*q2p-z[2]*q1p)*pow((z[245]+pow(z[242],2)+pow(
  z[243],2)+2*par->wind*z[2]*z[243]-2*par->wind*z[1]*z[242]),0.5);
  z[249] = z[246] - z[240];
  z[250] = par->FootCMy + z[207];
  z[251] = par->FootCMy + z[208];
  z[252] = z[209] - par->FootCMx;
  z[253] = z[210] - par->FootCMx;
  z[254] = par->bodyweight*RFootFx;
  z[255] = par->bodyweight*RFootFy;
  z[257] = par->bodyweight*RFootMz;
  z[258] = par->FootCMy + z[223];
  z[259] = par->FootCMy + z[224];
  z[260] = z[225] - par->FootCMx;
  z[261] = z[226] - par->FootCMx;
  z[262] = par->bodyweight*LFootFx;
  z[263] = par->bodyweight*LFootFy;
  z[266] = par->bodyweight*LFootMz;
  z[268] = mom1 - mom2;
  z[269] = mom3 + z[257];
  z[270] = mom2 - mom3;
  z[271] = -mom1 - mom4;
  z[272] = mom4 - mom5;
  z[273] = mom6 + z[266];
  z[274] = mom5 - mom6;
  z[275] = z[47]*z[49]*z[255] + z[48]*z[50]*z[255] + z[51]*z[53]*z[263] + 
  z[52]*z[54]*z[263] + z[254]*pow(z[47],2) + z[254]*pow(z[48],2) + z[262]*
  pow(z[51],2) + z[262]*pow(z[52],2) + z[1]*z[247] + z[2]*z[248] + pow(z[1],2)*
  z[249] + pow(z[2],2)*z[249] - z[233]*pow(z[47],2) - z[233]*pow(z[48],2) - 
  z[233]*pow(z[51],2) - z[233]*pow(z[52],2) - z[235]*z[47]*z[49] - z[235]*
  z[48]*z[50] - z[235]*z[51]*z[53] - z[235]*z[52]*z[54] - z[236]*pow(z[15],2) - 
  z[236]*pow(z[18],2) - z[236]*pow(z[37],2) - z[236]*pow(z[40],2) - z[237]*
  z[14]*z[15] - z[237]*z[17]*z[18] - z[237]*z[36]*z[37] - z[237]*z[39]*z[40] - 
  z[238]*pow(z[7],2) - z[238]*pow(z[8],2) - z[238]*pow(z[29],2) - z[238]*pow(
  z[30],2) - z[239]*z[7]*z[8] - z[239]*z[7]*z[9] - z[239]*z[29]*z[30] - 
  z[239]*z[29]*z[31];
  z[276] = z[47]*z[49]*z[254] + z[48]*z[50]*z[254] + z[51]*z[53]*z[262] + 
  z[52]*z[54]*z[262] + z[255]*pow(z[49],2) + z[255]*pow(z[50],2) + z[263]*
  pow(z[53],2) + z[263]*pow(z[54],2) + z[2]*z[247] - z[233]*z[47]*z[49] - 
  z[233]*z[48]*z[50] - z[233]*z[51]*z[53] - z[233]*z[52]*z[54] - z[235]*pow(
  z[49],2) - z[235]*pow(z[50],2) - z[235]*pow(z[53],2) - z[235]*pow(z[54],2) - 
  z[236]*z[14]*z[15] - z[236]*z[17]*z[18] - z[236]*z[36]*z[37] - z[236]*z[39]*
  z[40] - z[237]*pow(z[14],2) - z[237]*pow(z[17],2) - z[237]*pow(z[36],2) - 
  z[237]*pow(z[39],2) - z[238]*z[7]*z[8] - z[238]*z[7]*z[9] - z[238]*z[29]*
  z[30] - z[238]*z[29]*z[31] - z[239]*pow(z[7],2) - z[239]*pow(z[9],2) - 
  z[239]*pow(z[29],2) - z[239]*pow(z[31],2) - z[241]*pow(z[1],2) - z[241]*
  pow(z[2],2) - z[1]*z[248];
  z[277] = z[268] + z[269] + z[270] + z[271] + z[272] + z[273] + z[274] + q2*
  z[254] + q2*z[262] + z[236]*z[18]*z[19] + z[236]*z[40]*z[41] + z[237]*z[17]*
  z[19] + z[237]*z[39]*z[41] + z[47]*z[251]*z[254] + z[48]*z[252]*z[254] + 
  z[49]*z[251]*z[255] + z[50]*z[252]*z[255] + z[51]*z[259]*z[262] + z[52]*
  z[260]*z[262] + z[53]*z[259]*z[263] + z[54]*z[260]*z[263] + par->ThighCMy*(
  z[238]*z[7]+z[239]*z[9]) + par->ThighCMy*(z[238]*z[29]+z[239]*z[31]) + 
  par->TrunkCMy*(z[241]*z[2]-z[247]-z[1]*z[249]) - q1*z[255] - q1*z[263] - 
  par->ShankLen*z[14]*z[255] - par->ShankLen*z[15]*z[254] - par->ShankLen*
  z[36]*z[263] - par->ShankLen*z[37]*z[262] - par->ThighLen*z[7]*z[254] - 
  par->ThighLen*z[9]*z[255] - par->ThighLen*z[29]*z[262] - par->ThighLen*
  z[31]*z[263] - z[233]*z[47]*z[208] - z[233]*z[48]*z[209] - z[233]*z[51]*
  z[224] - z[233]*z[52]*z[225] - z[235]*z[49]*z[208] - z[235]*z[50]*z[209] - 
  z[235]*z[53]*z[224] - z[235]*z[54]*z[225] - z[236]*z[15]*z[201] - z[236]*
  z[37]*z[217] - z[237]*z[14]*z[201] - z[237]*z[36]*z[217];
  z[278] = z[268] + z[269] + z[270] + q2*z[254] + z[236]*z[18]*z[19] + z[237]*
  z[17]*z[19] + z[47]*z[251]*z[254] + z[48]*z[252]*z[254] + z[49]*z[251]*
  z[255] + z[50]*z[252]*z[255] + par->ThighCMy*(z[238]*z[7]+z[239]*z[9]) - q1*
  z[255] - par->ShankLen*z[14]*z[255] - par->ShankLen*z[15]*z[254] - par->ThighLen*
  z[7]*z[254] - par->ThighLen*z[9]*z[255] - z[233]*z[47]*z[208] - z[233]*
  z[48]*z[209] - z[235]*z[49]*z[208] - z[235]*z[50]*z[209] - z[236]*z[15]*
  z[201] - z[237]*z[14]*z[201];
  z[279] = z[269] + z[270] + q2*z[254] + z[47]*z[250]*z[254] + z[48]*z[253]*
  z[254] + z[49]*z[250]*z[255] + z[50]*z[253]*z[255] + par->ShankCMy*(z[236]*
  z[15]+z[237]*z[14]) - q1*z[255] - par->ShankLen*z[14]*z[255] - par->ShankLen*
  z[15]*z[254] - par->ThighLen*z[7]*z[254] - par->ThighLen*z[9]*z[255] - 
  z[233]*z[47]*z[207] - z[233]*z[48]*z[210] - z[235]*z[49]*z[207] - z[235]*
  z[50]*z[210];
  z[280] = par->FootCMy*z[233];
  z[281] = par->FootCMy*z[235];
  z[282] = par->FootCMx*z[233];
  z[283] = par->FootCMx*z[235];
  z[284] = z[269] + z[280]*z[47] + z[281]*z[49] + q2*z[254] - z[282]*z[48] - 
  z[283]*z[50] - q1*z[255] - par->ShankLen*z[14]*z[255] - par->ShankLen*z[15]*
  z[254] - par->ThighLen*z[7]*z[254] - par->ThighLen*z[9]*z[255];
  z[285] = z[272] + z[273] + z[274] + q2*z[262] + z[236]*z[40]*z[41] + z[237]*
  z[39]*z[41] + z[51]*z[259]*z[262] + z[52]*z[260]*z[262] + z[53]*z[259]*
  z[263] + z[54]*z[260]*z[263] + par->ThighCMy*(z[238]*z[29]+z[239]*z[31]) - 
  q1*z[263] - par->ShankLen*z[36]*z[263] - par->ShankLen*z[37]*z[262] - 
  par->ThighLen*z[29]*z[262] - par->ThighLen*z[31]*z[263] - z[233]*z[51]*
  z[224] - z[233]*z[52]*z[225] - z[235]*z[53]*z[224] - z[235]*z[54]*z[225] - 
  z[236]*z[37]*z[217] - z[237]*z[36]*z[217];
  z[286] = z[273] + z[274] + q2*z[262] + z[51]*z[258]*z[262] + z[52]*z[261]*
  z[262] + z[53]*z[258]*z[263] + z[54]*z[261]*z[263] + par->ShankCMy*(z[236]*
  z[37]+z[237]*z[36]) - q1*z[263] - par->ShankLen*z[36]*z[263] - par->ShankLen*
  z[37]*z[262] - par->ThighLen*z[29]*z[262] - par->ThighLen*z[31]*z[263] - 
  z[233]*z[51]*z[223] - z[233]*z[52]*z[226] - z[235]*z[53]*z[223] - z[235]*
  z[54]*z[226];
  z[287] = z[273] + z[280]*z[51] + z[281]*z[53] + q2*z[262] - z[282]*z[52] - 
  z[283]*z[54] - q1*z[263] - par->ShankLen*z[36]*z[263] - par->ShankLen*z[37]*
  z[262] - par->ThighLen*z[29]*z[262] - par->ThighLen*z[31]*z[263];
  z[288] = par->FootMass*(par->FootCMx*z[52]-par->FootCMy*z[51]);
  z[289] = par->FootMass*(pow(z[47],2)+pow(z[48],2)) + par->FootMass*(pow(
  z[51],2)+pow(z[52],2)) + par->ShankMass*(pow(z[15],2)+pow(z[18],2)) + 
  par->ShankMass*(pow(z[37],2)+pow(z[40],2)) + par->ThighMass*(pow(z[7],2)+
  pow(z[8],2)) + par->ThighMass*(pow(z[29],2)+pow(z[30],2)) + par->TrunkMass*(
  pow(z[1],2)+pow(z[2],2));
  z[290] = par->ThighMass*z[7]*(z[8]+z[9]) + par->ThighMass*z[29]*(z[30]+
  z[31]) + par->FootMass*(z[47]*z[49]+z[48]*z[50]) + par->FootMass*(z[51]*
  z[53]+z[52]*z[54]) + par->ShankMass*(z[14]*z[15]+z[17]*z[18]) + par->ShankMass*(
  z[36]*z[37]+z[39]*z[40]);
  z[291] = par->ThighCMy*par->ThighMass;
  z[292] = par->TrunkCMy*par->TrunkMass;
  z[293] = par->FootMass*(z[47]*z[208]+z[48]*z[209]) + par->FootMass*(z[51]*
  z[224]+z[52]*z[225]) + par->ShankMass*(z[15]*z[201]-z[18]*z[19]) + par->ShankMass*(
  z[37]*z[217]-z[40]*z[41]) - z[291]*z[7] - z[291]*z[29] - z[292]*z[1];
  z[294] = par->FootMass*(z[51]*z[224]+z[52]*z[225]) + par->ShankMass*(z[37]*
  z[217]-z[40]*z[41]) - z[291]*z[29];
  z[295] = par->ShankCMy*par->ShankMass;
  z[296] = par->FootMass*(z[51]*z[223]+z[52]*z[226]) - z[295]*z[37];
  z[297] = par->FootMass*(par->FootCMx*z[48]-par->FootCMy*z[47]);
  z[298] = par->FootMass*(z[47]*z[208]+z[48]*z[209]) + par->ShankMass*(z[15]*
  z[201]-z[18]*z[19]) - z[291]*z[7];
  z[299] = par->FootMass*(z[47]*z[207]+z[48]*z[210]) - z[295]*z[15];
  z[300] = par->TrunkMass*z[2]*z[199] + par->FootMass*(z[47]*z[214]+z[48]*
  z[215]) + par->FootMass*(z[51]*z[230]+z[52]*z[231]) + par->ShankMass*(z[15]*
  z[21]+z[18]*z[202]) + par->ShankMass*(z[37]*z[43]+z[40]*z[218]) - par->ThighMass*
  z[8]*z[200] - par->ThighMass*z[30]*z[216];
  z[301] = par->FootMass*(par->FootCMx*z[54]-par->FootCMy*z[53]);
  z[302] = par->FootMass*(pow(z[49],2)+pow(z[50],2)) + par->FootMass*(pow(
  z[53],2)+pow(z[54],2)) + par->ShankMass*(pow(z[14],2)+pow(z[17],2)) + 
  par->ShankMass*(pow(z[36],2)+pow(z[39],2)) + par->ThighMass*(pow(z[7],2)+
  pow(z[9],2)) + par->ThighMass*(pow(z[29],2)+pow(z[31],2)) + par->TrunkMass*(
  pow(z[1],2)+pow(z[2],2));
  z[303] = par->FootMass*(z[49]*z[208]+z[50]*z[209]) + par->FootMass*(z[53]*
  z[224]+z[54]*z[225]) + par->ShankMass*(z[14]*z[201]-z[17]*z[19]) + par->ShankMass*(
  z[36]*z[217]-z[39]*z[41]) - z[291]*z[9] - z[291]*z[31] - z[292]*z[2];
  z[304] = par->FootMass*(z[53]*z[224]+z[54]*z[225]) + par->ShankMass*(z[36]*
  z[217]-z[39]*z[41]) - z[291]*z[31];
  z[305] = par->FootMass*(z[53]*z[223]+z[54]*z[226]) - z[295]*z[36];
  z[306] = par->FootMass*(par->FootCMx*z[50]-par->FootCMy*z[49]);
  z[307] = par->FootMass*(z[49]*z[208]+z[50]*z[209]) + par->ShankMass*(z[14]*
  z[201]-z[17]*z[19]) - z[291]*z[9];
  z[308] = par->FootMass*(z[49]*z[207]+z[50]*z[210]) - z[295]*z[14];
  z[309] = par->FootMass*(z[49]*z[214]+z[50]*z[215]) + par->FootMass*(z[53]*
  z[230]+z[54]*z[231]) + par->ShankMass*(z[14]*z[21]+z[17]*z[202]) + par->ShankMass*(
  z[36]*z[43]+z[39]*z[218]) - par->ThighMass*z[7]*z[200] - par->ThighMass*
  z[29]*z[216] - par->TrunkMass*z[1]*z[199];
  z[310] = par->TrunkInertia + 2*par->FootInertia + 2*par->ShankInertia + 2*
  par->ThighInertia + par->TrunkMass*pow(par->TrunkCMy,2) + 2*par->ThighMass*
  pow(par->ThighCMy,2);
  z[311] = z[310] + par->FootMass*(pow(z[208],2)+pow(z[209],2)) + par->FootMass*(
  pow(z[224],2)+pow(z[225],2)) + par->ShankMass*(pow(z[19],2)+pow(z[201],2)) + 
  par->ShankMass*(pow(z[41],2)+pow(z[217],2));
  z[312] = par->FootInertia + par->ShankInertia + par->ThighInertia + par->ThighMass*
  pow(par->ThighCMy,2);
  z[313] = z[312] + par->FootMass*(pow(z[224],2)+pow(z[225],2)) + par->ShankMass*(
  pow(z[41],2)+pow(z[217],2));
  z[314] = par->FootInertia + par->ShankInertia;
  z[315] = z[314] + par->FootMass*(z[223]*z[224]+z[225]*z[226]) - z[295]*
  z[217];
  z[316] = par->FootInertia + par->FootMass*(par->FootCMx*z[225]-par->FootCMy*
  z[224]);
  z[317] = z[312] + par->FootMass*(pow(z[208],2)+pow(z[209],2)) + par->ShankMass*(
  pow(z[19],2)+pow(z[201],2));
  z[318] = z[314] + par->FootMass*(z[207]*z[208]+z[209]*z[210]) - z[295]*
  z[201];
  z[319] = par->FootInertia + par->FootMass*(par->FootCMx*z[209]-par->FootCMy*
  z[208]);
  z[320] = par->FootMass*(z[208]*z[214]+z[209]*z[215]) + par->FootMass*(
  z[224]*z[230]+z[225]*z[231]) - par->ShankMass*(z[19]*z[202]-z[201]*z[21]) - 
  par->ShankMass*(z[41]*z[218]-z[217]*z[43]);
  z[321] = par->FootMass*(z[208]*z[214]+z[209]*z[215]) - par->ShankMass*(
  z[19]*z[202]-z[201]*z[21]);
  z[322] = par->FootInertia + par->ShankInertia + par->ShankMass*pow(par->ShankCMy,
  2);
  z[323] = z[322] + par->FootMass*(pow(z[207],2)+pow(z[210],2));
  z[324] = par->FootInertia + par->FootMass*(par->FootCMx*z[210]-par->FootCMy*
  z[207]);
  z[325] = par->FootMass*(z[207]*z[214]+z[210]*z[215]) - z[295]*z[21];
  z[326] = par->FootInertia + par->FootMass*(pow(par->FootCMx,2)+pow(par->FootCMy,
  2));
  z[327] = par->FootMass*(par->FootCMx*z[215]-par->FootCMy*z[214]);
  z[328] = par->FootMass*(z[224]*z[230]+z[225]*z[231]) - par->ShankMass*(
  z[41]*z[218]-z[217]*z[43]);
  z[329] = z[322] + par->FootMass*(pow(z[223],2)+pow(z[226],2));
  z[330] = par->FootInertia + par->FootMass*(par->FootCMx*z[226]-par->FootCMy*
  z[223]);
  z[331] = par->FootMass*(z[223]*z[230]+z[226]*z[231]) - z[295]*z[43];
  z[332] = par->FootMass*(par->FootCMx*z[231]-par->FootCMy*z[230]);
  z[333] = -z[1]*q1p - z[2]*q2p;
  z[334] = par->airdrag*((par->TrunkCMy*q3p-z[1]*q1p-z[2]*q2p)*(z[242]*z[243]+
  z[243]*z[333]+par->wind*z[2]*z[242]+par->wind*z[2]*z[333])+(z[1]*q2p-z[2]*
  q1p)*(2*par->wind*z[1]*z[242]-z[245]-pow(z[242],2)-pow(z[243],2)-2*par->wind*
  z[2]*z[243]))/pow((z[245]+pow(z[242],2)+pow(z[243],2)+2*par->wind*z[2]*
  z[243]-2*par->wind*z[1]*z[242]),0.5);
  z[335] = par->airdrag*((z[1]*q2p-z[2]*q1p)*(z[242]*z[243]+z[243]*z[333]+
  par->wind*z[2]*z[242]+par->wind*z[2]*z[333])+(z[1]*q1p+z[2]*q2p)*(2*par->wind*
  z[1]*z[242]-z[245]-pow(z[242],2)-pow(z[243],2)-2*par->wind*z[2]*z[243]))/
  pow((z[245]+pow(z[242],2)+pow(z[243],2)+2*par->wind*z[2]*z[243]-2*par->wind*
  z[1]*z[242]),0.5);
  z[336] = z[244]*(z[242]*z[243]+z[243]*z[333]+par->wind*z[2]*z[242]+par->wind*
  z[2]*z[333])/pow((z[245]+pow(z[242],2)+pow(z[243],2)+2*par->wind*z[2]*
  z[243]-2*par->wind*z[1]*z[242]),0.5);
  z[337] = z[49]*z[60]*z[255] + z[50]*z[62]*z[255] + z[53]*z[73]*z[263] + 
  z[54]*z[75]*z[263] + z[255]*pow(z[47],2) + z[255]*pow(z[48],2) + z[263]*
  pow(z[51],2) + z[263]*pow(z[52],2) + 2*z[47]*z[60]*z[254] + 2*z[48]*z[62]*
  z[254] + 2*z[51]*z[73]*z[262] + 2*z[52]*z[75]*z[262] + z[1]*z[248] + z[1]*
  z[334] + z[2]*z[335] + pow(z[1],2)*z[336] + pow(z[2],2)*z[336] - 2*z[233]*
  z[47]*z[60] - 2*z[233]*z[48]*z[62] - 2*z[233]*z[51]*z[73] - 2*z[233]*z[52]*
  z[75] - 2*z[236]*z[15]*z[56] - 2*z[236]*z[18]*z[57] - 2*z[236]*z[37]*z[69] - 
  2*z[236]*z[40]*z[70] - 2*z[238]*z[7]*z[8] - 2*z[238]*z[8]*z[55] - 2*z[238]*
  z[29]*z[30] - 2*z[238]*z[30]*z[68] - z[235]*pow(z[47],2) - z[235]*pow(z[48],
  2) - z[235]*z[49]*z[60] - z[235]*z[50]*z[62] - z[235]*pow(z[51],2) - z[235]*
  pow(z[52],2) - z[235]*z[53]*z[73] - z[235]*z[54]*z[75] - z[237]*z[14]*z[56] - 
  z[237]*pow(z[15],2) - z[237]*z[17]*z[57] - z[237]*pow(z[18],2) - z[237]*
  z[36]*z[69] - z[237]*pow(z[37],2) - z[237]*z[39]*z[70] - z[237]*pow(z[40],2) - 
  z[239]*z[7]*z[55] - z[239]*pow(z[7],2) - z[239]*z[8]*z[9] - z[239]*pow(z[8],
  2) - z[239]*z[29]*z[68] - z[239]*pow(z[29],2) - z[239]*z[30]*z[31] - z[239]*
  pow(z[30],2) - z[2]*z[247];
  z[338] = par->TrunkMass*z[1]*z[199] + par->FootMass*(z[60]*z[214]+z[62]*
  z[215]) + par->FootMass*(z[73]*z[230]+z[75]*z[231]) + par->ShankMass*(z[56]*
  z[21]+z[57]*z[202]) + par->ShankMass*(z[69]*z[43]+z[70]*z[218]) - par->ThighMass*
  z[55]*z[200] - par->ThighMass*z[68]*z[216];
  z[339] = par->FootMass*(par->FootCMx*z[75]-par->FootCMy*z[73]);
  z[340] = 2*par->ThighMass*z[8]*(z[7]+z[55]) + 2*par->ThighMass*z[30]*(z[29]+
  z[68]) + 2*par->FootMass*(z[47]*z[60]+z[48]*z[62]) + 2*par->FootMass*(z[51]*
  z[73]+z[52]*z[75]) + 2*par->ShankMass*(z[15]*z[56]+z[18]*z[57]) + 2*par->ShankMass*(
  z[37]*z[69]+z[40]*z[70]);
  z[341] = par->ThighMass*z[7]*(z[7]+z[55]) + par->ThighMass*z[8]*(z[8]+z[9]) + 
  par->ThighMass*z[29]*(z[29]+z[68]) + par->ThighMass*z[30]*(z[30]+z[31]) + 
  par->FootMass*(pow(z[47],2)+pow(z[48],2)+z[49]*z[60]+z[50]*z[62]) + par->FootMass*(
  pow(z[51],2)+pow(z[52],2)+z[53]*z[73]+z[54]*z[75]) + par->ShankMass*(z[14]*
  z[56]+pow(z[15],2)+z[17]*z[57]+pow(z[18],2)) + par->ShankMass*(z[36]*z[69]+
  pow(z[37],2)+z[39]*z[70]+pow(z[40],2));
  z[342] = z[292]*z[2] + par->FootMass*(z[60]*z[208]+z[62]*z[209]) + par->FootMass*(
  z[73]*z[224]+z[75]*z[225]) - z[291]*z[8] - z[291]*z[30] - par->ShankMass*(
  z[19]*z[57]-z[56]*z[201]) - par->ShankMass*(z[41]*z[70]-z[69]*z[217]);
  z[343] = par->FootMass*(z[73]*z[224]+z[75]*z[225]) - z[291]*z[30] - par->ShankMass*(
  z[41]*z[70]-z[69]*z[217]);
  z[344] = par->FootMass*(z[73]*z[223]+z[75]*z[226]) - z[295]*z[69];
  z[345] = par->FootMass*(par->FootCMx*z[62]-par->FootCMy*z[60]);
  z[346] = par->FootMass*(z[60]*z[208]+z[62]*z[209]) - z[291]*z[8] - par->ShankMass*(
  z[19]*z[57]-z[56]*z[201]);
  z[347] = par->FootMass*(z[60]*z[207]+z[62]*z[210]) - z[295]*z[56];
  z[348] = z[49]*z[60]*z[255] + z[50]*z[62]*z[255] + z[255]*pow(z[47],2) + 
  z[255]*pow(z[48],2) + 2*z[47]*z[60]*z[254] + 2*z[48]*z[62]*z[254] - 2*
  z[233]*z[47]*z[60] - 2*z[233]*z[48]*z[62] - 2*z[236]*z[15]*z[56] - 2*z[236]*
  z[18]*z[57] - 2*z[238]*z[7]*z[8] - 2*z[238]*z[8]*z[55] - z[235]*pow(z[47],2) - 
  z[235]*pow(z[48],2) - z[235]*z[49]*z[60] - z[235]*z[50]*z[62] - z[237]*
  z[14]*z[56] - z[237]*pow(z[15],2) - z[237]*z[17]*z[57] - z[237]*pow(z[18],2) - 
  z[239]*z[7]*z[55] - z[239]*pow(z[7],2) - z[239]*z[8]*z[9] - z[239]*pow(z[8],
  2);
  z[349] = par->FootMass*(z[60]*z[214]+z[62]*z[215]) + par->ShankMass*(z[56]*
  z[21]+z[57]*z[202]) - par->ThighMass*z[55]*z[200];
  z[350] = 2*par->ThighMass*z[8]*(z[7]+z[55]) + 2*par->FootMass*(z[47]*z[60]+
  z[48]*z[62]) + 2*par->ShankMass*(z[15]*z[56]+z[18]*z[57]);
  z[351] = par->ThighMass*z[7]*(z[7]+z[55]) + par->ThighMass*z[8]*(z[8]+z[9]) + 
  par->FootMass*(pow(z[47],2)+pow(z[48],2)+z[49]*z[60]+z[50]*z[62]) + par->ShankMass*(
  z[14]*z[56]+pow(z[15],2)+z[17]*z[57]+pow(z[18],2));
  z[352] = z[47]*z[65]*z[255] + z[48]*z[66]*z[255] + z[49]*z[61]*z[255] + 
  z[50]*z[63]*z[255] + 2*z[47]*z[61]*z[254] + 2*z[48]*z[63]*z[254] - 2*z[233]*
  z[47]*z[61] - 2*z[233]*z[48]*z[63] - 2*z[236]*z[15]*z[18] - 2*z[236]*z[18]*
  z[58] - z[235]*z[47]*z[65] - z[235]*z[48]*z[66] - z[235]*z[49]*z[61] - 
  z[235]*z[50]*z[63] - z[237]*z[14]*z[18] - z[237]*z[15]*z[17] - z[237]*z[17]*
  z[58] - z[237]*z[18]*z[59];
  z[353] = (z[5]*z[12]-z[6]*z[13])*z[11];
  z[354] = (z[5]*z[13]+z[6]*z[12])*z[11];
  z[355] = par->ShankMass*(z[18]*z[21]+z[58]*z[202]+z[5]*z[15]*z[11]-z[6]*
  z[18]*z[11]) - par->FootMass*(z[48]*z[354]-z[47]*z[353]-z[61]*z[214]-z[63]*
  z[215]);
  z[356] = 2*par->ShankMass*z[18]*(z[15]+z[58]) + 2*par->FootMass*(z[47]*
  z[61]+z[48]*z[63]);
  z[357] = par->FootMass*(z[47]*z[65]+z[48]*z[66]+z[49]*z[61]+z[50]*z[63]) + 
  par->ShankMass*(z[14]*z[18]+z[15]*z[17]+z[17]*z[58]+z[18]*z[59]);
  z[358] = par->ThighLen*(z[5]*z[13]+z[6]*z[12]);
  z[359] = par->ThighLen*(z[5]*z[12]-z[6]*z[13]);
  z[360] = par->ShankMass*(z[18]*z[201]-z[19]*z[58]-par->ThighLen*z[5]*z[18]-
  par->ThighLen*z[6]*z[15]) - par->FootMass*(z[47]*z[358]+z[48]*z[359]-z[61]*
  z[208]-z[63]*z[209]);
  z[361] = par->FootMass*(par->FootCMx*z[63]-par->FootCMy*z[61]);
  z[362] = par->FootMass*(z[61]*z[207]+z[63]*z[210]) - z[295]*z[18];
  z[363] = z[47]*z[50]*z[255] + z[48]*z[49]*z[255] + z[48]*z[67]*z[255] + 
  z[50]*z[64]*z[255] + 2*z[47]*z[48]*z[254] + 2*z[48]*z[64]*z[254] - 2*z[233]*
  z[47]*z[48] - 2*z[233]*z[48]*z[64] - z[235]*z[47]*z[50] - z[235]*z[48]*
  z[49] - z[235]*z[48]*z[67] - z[235]*z[50]*z[64];
  z[364] = -z[12]*z[21] - z[13]*z[24];
  z[365] = par->FootMass*(z[47]*z[212]+z[48]*z[214]+z[48]*z[364]+z[64]*z[215]);
  z[366] = par->FootMass*z[48]*(z[47]+z[64]);
  z[367] = par->FootMass*(z[47]*z[50]+z[48]*z[49]+z[48]*z[67]+z[50]*z[64]);
  z[368] = z[13]*z[19] - z[12]*z[20];
  z[369] = par->FootMass*(z[47]*z[205]+z[48]*z[208]+z[48]*z[368]+z[64]*z[209]);
  z[370] = par->FootMass*(par->FootCMx*z[64]-par->FootCMy*z[48]);
  z[371] = par->FootMass*(z[48]*z[207]+z[64]*z[210]-par->ShankLen*z[12]*z[48]-
  par->ShankLen*z[13]*z[47]);
  z[372] = z[53]*z[73]*z[263] + z[54]*z[75]*z[263] + z[263]*pow(z[51],2) + 
  z[263]*pow(z[52],2) + 2*z[51]*z[73]*z[262] + 2*z[52]*z[75]*z[262] - 2*
  z[233]*z[51]*z[73] - 2*z[233]*z[52]*z[75] - 2*z[236]*z[37]*z[69] - 2*z[236]*
  z[40]*z[70] - 2*z[238]*z[29]*z[30] - 2*z[238]*z[30]*z[68] - z[235]*pow(
  z[51],2) - z[235]*pow(z[52],2) - z[235]*z[53]*z[73] - z[235]*z[54]*z[75] - 
  z[237]*z[36]*z[69] - z[237]*pow(z[37],2) - z[237]*z[39]*z[70] - z[237]*pow(
  z[40],2) - z[239]*z[29]*z[68] - z[239]*pow(z[29],2) - z[239]*z[30]*z[31] - 
  z[239]*pow(z[30],2);
  z[373] = par->FootMass*(z[73]*z[230]+z[75]*z[231]) + par->ShankMass*(z[69]*
  z[43]+z[70]*z[218]) - par->ThighMass*z[68]*z[216];
  z[374] = 2*par->ThighMass*z[30]*(z[29]+z[68]) + 2*par->FootMass*(z[51]*
  z[73]+z[52]*z[75]) + 2*par->ShankMass*(z[37]*z[69]+z[40]*z[70]);
  z[375] = par->ThighMass*z[29]*(z[29]+z[68]) + par->ThighMass*z[30]*(z[30]+
  z[31]) + par->FootMass*(pow(z[51],2)+pow(z[52],2)+z[53]*z[73]+z[54]*z[75]) + 
  par->ShankMass*(z[36]*z[69]+pow(z[37],2)+z[39]*z[70]+pow(z[40],2));
  z[376] = z[51]*z[78]*z[263] + z[52]*z[79]*z[263] + z[53]*z[74]*z[263] + 
  z[54]*z[76]*z[263] + 2*z[51]*z[74]*z[262] + 2*z[52]*z[76]*z[262] - 2*z[233]*
  z[51]*z[74] - 2*z[233]*z[52]*z[76] - 2*z[236]*z[37]*z[40] - 2*z[236]*z[40]*
  z[71] - z[235]*z[51]*z[78] - z[235]*z[52]*z[79] - z[235]*z[53]*z[74] - 
  z[235]*z[54]*z[76] - z[237]*z[36]*z[40] - z[237]*z[37]*z[39] - z[237]*z[39]*
  z[71] - z[237]*z[40]*z[72];
  z[377] = (z[27]*z[34]-z[28]*z[35])*z[33];
  z[378] = (z[27]*z[35]+z[28]*z[34])*z[33];
  z[379] = par->ShankMass*(z[40]*z[43]+z[71]*z[218]+z[27]*z[37]*z[33]-z[28]*
  z[40]*z[33]) - par->FootMass*(z[52]*z[378]-z[51]*z[377]-z[74]*z[230]-z[76]*
  z[231]);
  z[380] = par->FootMass*(par->FootCMx*z[76]-par->FootCMy*z[74]);
  z[381] = 2*par->ShankMass*z[40]*(z[37]+z[71]) + 2*par->FootMass*(z[51]*
  z[74]+z[52]*z[76]);
  z[382] = par->FootMass*(z[51]*z[78]+z[52]*z[79]+z[53]*z[74]+z[54]*z[76]) + 
  par->ShankMass*(z[36]*z[40]+z[37]*z[39]+z[39]*z[71]+z[40]*z[72]);
  z[383] = par->ThighLen*(z[27]*z[35]+z[28]*z[34]);
  z[384] = par->ThighLen*(z[27]*z[34]-z[28]*z[35]);
  z[385] = par->ShankMass*(z[40]*z[217]-z[41]*z[71]-par->ThighLen*z[27]*z[40]-
  par->ThighLen*z[28]*z[37]) - par->FootMass*(z[51]*z[383]+z[52]*z[384]-z[74]*
  z[224]-z[76]*z[225]);
  z[386] = par->FootMass*(z[74]*z[223]+z[76]*z[226]) - z[295]*z[40];
  z[387] = z[51]*z[54]*z[263] + z[52]*z[53]*z[263] + z[52]*z[80]*z[263] + 
  z[54]*z[77]*z[263] + 2*z[51]*z[52]*z[262] + 2*z[52]*z[77]*z[262] - 2*z[233]*
  z[51]*z[52] - 2*z[233]*z[52]*z[77] - z[235]*z[51]*z[54] - z[235]*z[52]*
  z[53] - z[235]*z[52]*z[80] - z[235]*z[54]*z[77];
  z[388] = -z[34]*z[43] - z[35]*z[46];
  z[389] = par->FootMass*(z[51]*z[228]+z[52]*z[230]+z[52]*z[388]+z[77]*z[231]);
  z[390] = par->FootMass*(par->FootCMx*z[77]-par->FootCMy*z[52]);
  z[391] = par->FootMass*z[52]*(z[51]+z[77]);
  z[392] = par->FootMass*(z[51]*z[54]+z[52]*z[53]+z[52]*z[80]+z[54]*z[77]);
  z[393] = z[35]*z[41] - z[34]*z[42];
  z[394] = par->FootMass*(z[51]*z[221]+z[52]*z[224]+z[52]*z[393]+z[77]*z[225]);
  z[395] = par->FootMass*(z[52]*z[223]+z[77]*z[226]-par->ShankLen*z[34]*z[52]-
  par->ShankLen*z[35]*z[51]);
  z[396] = z[49]*z[60]*z[254] + z[50]*z[62]*z[254] + z[53]*z[73]*z[262] + 
  z[54]*z[75]*z[262] + z[254]*pow(z[47],2) + z[254]*pow(z[48],2) + z[262]*
  pow(z[51],2) + z[262]*pow(z[52],2) + 2*z[47]*z[49]*z[255] + 2*z[48]*z[50]*
  z[255] + 2*z[51]*z[53]*z[263] + 2*z[52]*z[54]*z[263] + z[1]*z[247] + z[2]*
  z[248] + z[2]*z[334] - 2*z[235]*z[47]*z[49] - 2*z[235]*z[48]*z[50] - 2*
  z[235]*z[51]*z[53] - 2*z[235]*z[52]*z[54] - 2*z[237]*z[14]*z[15] - 2*z[237]*
  z[17]*z[18] - 2*z[237]*z[36]*z[37] - 2*z[237]*z[39]*z[40] - 2*z[239]*z[7]*
  z[8] - 2*z[239]*z[7]*z[9] - 2*z[239]*z[29]*z[30] - 2*z[239]*z[29]*z[31] - 
  z[233]*pow(z[47],2) - z[233]*pow(z[48],2) - z[233]*z[49]*z[60] - z[233]*
  z[50]*z[62] - z[233]*pow(z[51],2) - z[233]*pow(z[52],2) - z[233]*z[53]*
  z[73] - z[233]*z[54]*z[75] - z[236]*z[14]*z[56] - z[236]*pow(z[15],2) - 
  z[236]*z[17]*z[57] - z[236]*pow(z[18],2) - z[236]*z[36]*z[69] - z[236]*pow(
  z[37],2) - z[236]*z[39]*z[70] - z[236]*pow(z[40],2) - z[238]*z[7]*z[55] - 
  z[238]*pow(z[7],2) - z[238]*z[8]*z[9] - z[238]*pow(z[8],2) - z[238]*z[29]*
  z[68] - z[238]*pow(z[29],2) - z[238]*z[30]*z[31] - z[238]*pow(z[30],2) - 
  z[1]*z[335];
  z[397] = 2*par->ThighMass*z[7]*(z[8]+z[9]) + 2*par->ThighMass*z[29]*(z[30]+
  z[31]) + 2*par->FootMass*(z[47]*z[49]+z[48]*z[50]) + 2*par->FootMass*(z[51]*
  z[53]+z[52]*z[54]) + 2*par->ShankMass*(z[14]*z[15]+z[17]*z[18]) + 2*par->ShankMass*(
  z[36]*z[37]+z[39]*z[40]);
  z[398] = z[49]*z[60]*z[254] + z[50]*z[62]*z[254] + z[254]*pow(z[47],2) + 
  z[254]*pow(z[48],2) + 2*z[47]*z[49]*z[255] + 2*z[48]*z[50]*z[255] - 2*
  z[235]*z[47]*z[49] - 2*z[235]*z[48]*z[50] - 2*z[237]*z[14]*z[15] - 2*z[237]*
  z[17]*z[18] - 2*z[239]*z[7]*z[8] - 2*z[239]*z[7]*z[9] - z[233]*pow(z[47],2) - 
  z[233]*pow(z[48],2) - z[233]*z[49]*z[60] - z[233]*z[50]*z[62] - z[236]*
  z[14]*z[56] - z[236]*pow(z[15],2) - z[236]*z[17]*z[57] - z[236]*pow(z[18],2) - 
  z[238]*z[7]*z[55] - z[238]*pow(z[7],2) - z[238]*z[8]*z[9] - z[238]*pow(z[8],
  2);
  z[399] = par->FootMass*(z[47]*z[214]+z[48]*z[215]) + par->ShankMass*(z[15]*
  z[21]+z[18]*z[202]) - par->ThighMass*z[8]*z[200];
  z[400] = 2*par->ThighMass*z[7]*(z[8]+z[9]) + 2*par->FootMass*(z[47]*z[49]+
  z[48]*z[50]) + 2*par->ShankMass*(z[14]*z[15]+z[17]*z[18]);
  z[401] = z[47]*z[65]*z[254] + z[48]*z[66]*z[254] + z[49]*z[61]*z[254] + 
  z[50]*z[63]*z[254] + 2*z[49]*z[65]*z[255] + 2*z[50]*z[66]*z[255] - 2*z[235]*
  z[49]*z[65] - 2*z[235]*z[50]*z[66] - 2*z[237]*z[14]*z[17] - 2*z[237]*z[17]*
  z[59] - z[233]*z[47]*z[65] - z[233]*z[48]*z[66] - z[233]*z[49]*z[61] - 
  z[233]*z[50]*z[63] - z[236]*z[14]*z[18] - z[236]*z[15]*z[17] - z[236]*z[17]*
  z[58] - z[236]*z[18]*z[59];
  z[402] = par->ShankMass*(z[17]*z[21]+z[59]*z[202]+z[5]*z[14]*z[11]-z[6]*
  z[17]*z[11]) - par->FootMass*(z[50]*z[354]-z[49]*z[353]-z[65]*z[214]-z[66]*
  z[215]);
  z[403] = 2*par->ShankMass*z[17]*(z[14]+z[59]) + 2*par->FootMass*(z[49]*
  z[65]+z[50]*z[66]);
  z[404] = par->ShankMass*(z[17]*z[201]-z[19]*z[59]-par->ThighLen*z[5]*z[17]-
  par->ThighLen*z[6]*z[14]) - par->FootMass*(z[49]*z[358]+z[50]*z[359]-z[65]*
  z[208]-z[66]*z[209]);
  z[405] = par->FootMass*(par->FootCMx*z[66]-par->FootCMy*z[65]);
  z[406] = par->FootMass*(z[65]*z[207]+z[66]*z[210]) - z[295]*z[17];
  z[407] = z[47]*z[50]*z[254] + z[48]*z[49]*z[254] + z[48]*z[67]*z[254] + 
  z[50]*z[64]*z[254] + 2*z[49]*z[50]*z[255] + 2*z[50]*z[67]*z[255] - 2*z[235]*
  z[49]*z[50] - 2*z[235]*z[50]*z[67] - z[233]*z[47]*z[50] - z[233]*z[48]*
  z[49] - z[233]*z[48]*z[67] - z[233]*z[50]*z[64];
  z[408] = par->FootMass*(z[49]*z[212]+z[50]*z[214]+z[50]*z[364]+z[67]*z[215]);
  z[409] = par->FootMass*z[50]*(z[49]+z[67]);
  z[410] = par->FootMass*(z[49]*z[205]+z[50]*z[208]+z[50]*z[368]+z[67]*z[209]);
  z[411] = par->FootMass*(par->FootCMx*z[67]-par->FootCMy*z[50]);
  z[412] = par->FootMass*(z[50]*z[207]+z[67]*z[210]-par->ShankLen*z[12]*z[50]-
  par->ShankLen*z[13]*z[49]);
  z[413] = z[53]*z[73]*z[262] + z[54]*z[75]*z[262] + z[262]*pow(z[51],2) + 
  z[262]*pow(z[52],2) + 2*z[51]*z[53]*z[263] + 2*z[52]*z[54]*z[263] - 2*
  z[235]*z[51]*z[53] - 2*z[235]*z[52]*z[54] - 2*z[237]*z[36]*z[37] - 2*z[237]*
  z[39]*z[40] - 2*z[239]*z[29]*z[30] - 2*z[239]*z[29]*z[31] - z[233]*pow(
  z[51],2) - z[233]*pow(z[52],2) - z[233]*z[53]*z[73] - z[233]*z[54]*z[75] - 
  z[236]*z[36]*z[69] - z[236]*pow(z[37],2) - z[236]*z[39]*z[70] - z[236]*pow(
  z[40],2) - z[238]*z[29]*z[68] - z[238]*pow(z[29],2) - z[238]*z[30]*z[31] - 
  z[238]*pow(z[30],2);
  z[414] = par->FootMass*(z[51]*z[230]+z[52]*z[231]) + par->ShankMass*(z[37]*
  z[43]+z[40]*z[218]) - par->ThighMass*z[30]*z[216];
  z[415] = 2*par->ThighMass*z[29]*(z[30]+z[31]) + 2*par->FootMass*(z[51]*
  z[53]+z[52]*z[54]) + 2*par->ShankMass*(z[36]*z[37]+z[39]*z[40]);
  z[416] = z[51]*z[78]*z[262] + z[52]*z[79]*z[262] + z[53]*z[74]*z[262] + 
  z[54]*z[76]*z[262] + 2*z[53]*z[78]*z[263] + 2*z[54]*z[79]*z[263] - 2*z[235]*
  z[53]*z[78] - 2*z[235]*z[54]*z[79] - 2*z[237]*z[36]*z[39] - 2*z[237]*z[39]*
  z[72] - z[233]*z[51]*z[78] - z[233]*z[52]*z[79] - z[233]*z[53]*z[74] - 
  z[233]*z[54]*z[76] - z[236]*z[36]*z[40] - z[236]*z[37]*z[39] - z[236]*z[39]*
  z[71] - z[236]*z[40]*z[72];
  z[417] = par->ShankMass*(z[39]*z[43]+z[72]*z[218]+z[27]*z[36]*z[33]-z[28]*
  z[39]*z[33]) - par->FootMass*(z[54]*z[378]-z[53]*z[377]-z[78]*z[230]-z[79]*
  z[231]);
  z[418] = par->FootMass*(par->FootCMx*z[79]-par->FootCMy*z[78]);
  z[419] = 2*par->ShankMass*z[39]*(z[36]+z[72]) + 2*par->FootMass*(z[53]*
  z[78]+z[54]*z[79]);
  z[420] = par->ShankMass*(z[39]*z[217]-z[41]*z[72]-par->ThighLen*z[27]*z[39]-
  par->ThighLen*z[28]*z[36]) - par->FootMass*(z[53]*z[383]+z[54]*z[384]-z[78]*
  z[224]-z[79]*z[225]);
  z[421] = par->FootMass*(z[78]*z[223]+z[79]*z[226]) - z[295]*z[39];
  z[422] = z[51]*z[54]*z[262] + z[52]*z[53]*z[262] + z[52]*z[80]*z[262] + 
  z[54]*z[77]*z[262] + 2*z[53]*z[54]*z[263] + 2*z[54]*z[80]*z[263] - 2*z[235]*
  z[53]*z[54] - 2*z[235]*z[54]*z[80] - z[233]*z[51]*z[54] - z[233]*z[52]*
  z[53] - z[233]*z[52]*z[80] - z[233]*z[54]*z[77];
  z[423] = par->FootMass*(z[53]*z[228]+z[54]*z[230]+z[54]*z[388]+z[80]*z[231]);
  z[424] = par->FootMass*(par->FootCMx*z[80]-par->FootCMy*z[54]);
  z[425] = par->FootMass*z[54]*(z[53]+z[80]);
  z[426] = par->FootMass*(z[53]*z[221]+z[54]*z[224]+z[54]*z[393]+z[80]*z[225]);
  z[427] = par->FootMass*(z[54]*z[223]+z[80]*z[226]-par->ShankLen*z[34]*z[54]-
  par->ShankLen*z[35]*z[53]);
  z[428] = z[236]*z[19]*z[57] + z[236]*z[41]*z[70] + z[237]*z[18]*z[19] + 
  z[237]*z[40]*z[41] + z[47]*z[251]*z[255] + z[48]*z[252]*z[255] + z[51]*
  z[259]*z[263] + z[52]*z[260]*z[263] + z[60]*z[251]*z[254] + z[62]*z[252]*
  z[254] + z[73]*z[259]*z[262] + z[75]*z[260]*z[262] + par->ThighCMy*(z[238]*
  z[8]+z[239]*z[7]) + par->ThighCMy*(z[238]*z[30]+z[239]*z[29]) - par->ShankLen*
  z[15]*z[255] - par->ShankLen*z[37]*z[263] - par->ShankLen*z[56]*z[254] - 
  par->ShankLen*z[69]*z[262] - par->ThighLen*z[7]*z[255] - par->ThighLen*z[8]*
  z[254] - par->ThighLen*z[29]*z[263] - par->ThighLen*z[30]*z[262] - z[233]*
  z[60]*z[208] - z[233]*z[62]*z[209] - z[233]*z[73]*z[224] - z[233]*z[75]*
  z[225] - z[235]*z[47]*z[208] - z[235]*z[48]*z[209] - z[235]*z[51]*z[224] - 
  z[235]*z[52]*z[225] - z[236]*z[56]*z[201] - z[236]*z[69]*z[217] - z[237]*
  z[15]*z[201] - z[237]*z[37]*z[217] - par->TrunkCMy*(z[334]+z[1]*z[336]-
  z[241]*z[1]-z[2]*z[249]);
  z[429] = z[236]*z[19]*z[57] + z[237]*z[18]*z[19] + z[47]*z[251]*z[255] + 
  z[48]*z[252]*z[255] + z[60]*z[251]*z[254] + z[62]*z[252]*z[254] + par->ThighCMy*(
  z[238]*z[8]+z[239]*z[7]) - par->ShankLen*z[15]*z[255] - par->ShankLen*z[56]*
  z[254] - par->ThighLen*z[7]*z[255] - par->ThighLen*z[8]*z[254] - z[233]*
  z[60]*z[208] - z[233]*z[62]*z[209] - z[235]*z[47]*z[208] - z[235]*z[48]*
  z[209] - z[236]*z[56]*z[201] - z[237]*z[15]*z[201];
  z[430] = par->ThighLen*z[236];
  z[431] = par->ThighLen*z[237];
  z[432] = z[233]*z[47]*z[358] + z[233]*z[48]*z[359] + z[235]*z[49]*z[358] + 
  z[235]*z[50]*z[359] + z[236]*z[19]*z[58] + z[237]*z[19]*z[59] + z[430]*z[5]*
  z[18] + z[430]*z[6]*z[15] + z[431]*z[5]*z[17] + z[431]*z[6]*z[14] + z[61]*
  z[251]*z[254] + z[63]*z[252]*z[254] + z[65]*z[251]*z[255] + z[66]*z[252]*
  z[255] - par->ShankLen*z[17]*z[255] - par->ShankLen*z[18]*z[254] - z[233]*
  z[61]*z[208] - z[233]*z[63]*z[209] - z[235]*z[65]*z[208] - z[235]*z[66]*
  z[209] - z[236]*z[18]*z[201] - z[237]*z[17]*z[201] - z[47]*z[254]*z[358] - 
  z[48]*z[254]*z[359] - z[49]*z[255]*z[358] - z[50]*z[255]*z[359];
  z[433] = par->FootMass*(z[208]*z[353]-z[209]*z[354]-z[358]*z[214]-z[359]*
  z[215]) - par->ShankMass*(par->ThighLen*z[5]*z[202]+par->ThighLen*z[6]*
  z[21]-z[5]*z[201]*z[11]-z[6]*z[19]*z[11]);
  z[434] = par->ShankMass*par->ThighLen;
  z[435] = 2*z[434]*(z[5]*z[19]-z[6]*z[201]) - 2*par->FootMass*(z[208]*z[358]+
  z[209]*z[359]);
  z[436] = par->ThighLen*z[295];
  z[437] = z[436]*z[6] - par->FootMass*(z[207]*z[358]+z[210]*z[359]);
  z[438] = par->FootMass*(par->FootCMx*z[359]-par->FootCMy*z[358]);
  z[439] = z[47]*z[205]*z[254] + z[48]*z[251]*z[254] + z[48]*z[254]*z[368] + 
  z[49]*z[205]*z[255] + z[50]*z[251]*z[255] + z[50]*z[255]*z[368] + z[64]*
  z[252]*z[254] + z[67]*z[252]*z[255] - z[233]*z[47]*z[205] - z[233]*z[48]*
  z[208] - z[233]*z[48]*z[368] - z[233]*z[64]*z[209] - z[235]*z[49]*z[205] - 
  z[235]*z[50]*z[208] - z[235]*z[50]*z[368] - z[235]*z[67]*z[209];
  z[440] = par->FootMass*(z[205]*z[214]+z[208]*z[212]+z[209]*z[364]+z[368]*
  z[215]);
  z[441] = par->FootMass*(z[205]*z[208]+z[209]*z[368]);
  z[442] = par->FootMass*(z[205]*z[207]+z[210]*z[368]-par->ShankLen*z[12]*
  z[209]-par->ShankLen*z[13]*z[208]);
  z[443] = par->FootMass*(par->FootCMx*z[368]-par->FootCMy*z[205]);
  z[444] = z[236]*z[41]*z[70] + z[237]*z[40]*z[41] + z[51]*z[259]*z[263] + 
  z[52]*z[260]*z[263] + z[73]*z[259]*z[262] + z[75]*z[260]*z[262] + par->ThighCMy*(
  z[238]*z[30]+z[239]*z[29]) - par->ShankLen*z[37]*z[263] - par->ShankLen*
  z[69]*z[262] - par->ThighLen*z[29]*z[263] - par->ThighLen*z[30]*z[262] - 
  z[233]*z[73]*z[224] - z[233]*z[75]*z[225] - z[235]*z[51]*z[224] - z[235]*
  z[52]*z[225] - z[236]*z[69]*z[217] - z[237]*z[37]*z[217];
  z[445] = z[233]*z[51]*z[383] + z[233]*z[52]*z[384] + z[235]*z[53]*z[383] + 
  z[235]*z[54]*z[384] + z[236]*z[41]*z[71] + z[237]*z[41]*z[72] + z[430]*
  z[27]*z[40] + z[430]*z[28]*z[37] + z[431]*z[27]*z[39] + z[431]*z[28]*z[36] + 
  z[74]*z[259]*z[262] + z[76]*z[260]*z[262] + z[78]*z[259]*z[263] + z[79]*
  z[260]*z[263] - par->ShankLen*z[39]*z[263] - par->ShankLen*z[40]*z[262] - 
  z[233]*z[74]*z[224] - z[233]*z[76]*z[225] - z[235]*z[78]*z[224] - z[235]*
  z[79]*z[225] - z[236]*z[40]*z[217] - z[237]*z[39]*z[217] - z[51]*z[262]*
  z[383] - z[52]*z[262]*z[384] - z[53]*z[263]*z[383] - z[54]*z[263]*z[384];
  z[446] = par->FootMass*(z[224]*z[377]-z[225]*z[378]-z[383]*z[230]-z[384]*
  z[231]) - par->ShankMass*(par->ThighLen*z[27]*z[218]+par->ThighLen*z[28]*
  z[43]-z[27]*z[217]*z[33]-z[28]*z[41]*z[33]);
  z[447] = 2*z[434]*(z[27]*z[41]-z[28]*z[217]) - 2*par->FootMass*(z[224]*
  z[383]+z[225]*z[384]);
  z[448] = z[436]*z[28] - par->FootMass*(z[223]*z[383]+z[226]*z[384]);
  z[449] = par->FootMass*(par->FootCMx*z[384]-par->FootCMy*z[383]);
  z[450] = z[51]*z[221]*z[262] + z[52]*z[259]*z[262] + z[52]*z[262]*z[393] + 
  z[53]*z[221]*z[263] + z[54]*z[259]*z[263] + z[54]*z[263]*z[393] + z[77]*
  z[260]*z[262] + z[80]*z[260]*z[263] - z[233]*z[51]*z[221] - z[233]*z[52]*
  z[224] - z[233]*z[52]*z[393] - z[233]*z[77]*z[225] - z[235]*z[53]*z[221] - 
  z[235]*z[54]*z[224] - z[235]*z[54]*z[393] - z[235]*z[80]*z[225];
  z[451] = par->FootMass*(z[221]*z[230]+z[224]*z[228]+z[225]*z[388]+z[393]*
  z[231]);
  z[452] = par->FootMass*(z[221]*z[224]+z[225]*z[393]);
  z[453] = par->FootMass*(z[221]*z[223]+z[226]*z[393]-par->ShankLen*z[34]*
  z[225]-par->ShankLen*z[35]*z[224]);
  z[454] = par->FootMass*(par->FootCMx*z[393]-par->FootCMy*z[221]);
  z[455] = z[47]*z[250]*z[255] + z[48]*z[253]*z[255] + z[60]*z[250]*z[254] + 
  z[62]*z[253]*z[254] + par->ShankCMy*(z[236]*z[56]+z[237]*z[15]) - par->ShankLen*
  z[15]*z[255] - par->ShankLen*z[56]*z[254] - par->ThighLen*z[7]*z[255] - 
  par->ThighLen*z[8]*z[254] - z[233]*z[60]*z[207] - z[233]*z[62]*z[210] - 
  z[235]*z[47]*z[207] - z[235]*z[48]*z[210];
  z[456] = z[61]*z[250]*z[254] + z[63]*z[253]*z[254] + z[65]*z[250]*z[255] + 
  z[66]*z[253]*z[255] + par->ShankCMy*(z[236]*z[18]+z[237]*z[17]) - par->ShankLen*
  z[17]*z[255] - par->ShankLen*z[18]*z[254] - z[233]*z[61]*z[207] - z[233]*
  z[63]*z[210] - z[235]*z[65]*z[207] - z[235]*z[66]*z[210];
  z[457] = par->FootMass*(z[207]*z[353]-z[210]*z[354]) - z[295]*z[5]*z[11];
  z[458] = par->ShankLen*z[233];
  z[459] = par->ShankLen*z[235];
  z[460] = z[458]*z[12]*z[48] + z[458]*z[13]*z[47] + z[459]*z[12]*z[50] + 
  z[459]*z[13]*z[49] + z[48]*z[250]*z[254] + z[50]*z[250]*z[255] + z[64]*
  z[253]*z[254] + z[67]*z[253]*z[255] - z[233]*z[48]*z[207] - z[233]*z[64]*
  z[210] - z[235]*z[50]*z[207] - z[235]*z[67]*z[210] - par->ShankLen*z[12]*
  z[48]*z[254] - par->ShankLen*z[12]*z[50]*z[255] - par->ShankLen*z[13]*z[47]*
  z[254] - par->ShankLen*z[13]*z[49]*z[255];
  z[461] = par->FootMass*(z[207]*z[212]+z[210]*z[364]-par->ShankLen*z[12]*
  z[215]-par->ShankLen*z[13]*z[214]);
  z[462] = par->FootMass*par->ShankLen;
  z[463] = z[462]*(z[12]*z[210]+z[13]*z[207]);
  z[464] = z[462]*(par->FootCMx*z[12]-par->FootCMy*z[13]);
  z[465] = z[280]*z[60] + z[281]*z[47] - z[282]*z[62] - z[283]*z[48] - par->ShankLen*
  z[15]*z[255] - par->ShankLen*z[56]*z[254] - par->ThighLen*z[7]*z[255] - 
  par->ThighLen*z[8]*z[254];
  z[466] = z[280]*z[61] + z[281]*z[65] - z[282]*z[63] - z[283]*z[66] - par->ShankLen*
  z[17]*z[255] - par->ShankLen*z[18]*z[254];
  z[467] = par->FootMass*(par->FootCMx*z[354]+par->FootCMy*z[353]);
  z[468] = z[280]*z[48] + z[281]*z[50] - z[282]*z[64] - z[283]*z[67];
  z[469] = par->FootMass*(par->FootCMx*z[364]-par->FootCMy*z[212]);
  z[470] = z[51]*z[258]*z[263] + z[52]*z[261]*z[263] + z[73]*z[258]*z[262] + 
  z[75]*z[261]*z[262] + par->ShankCMy*(z[236]*z[69]+z[237]*z[37]) - par->ShankLen*
  z[37]*z[263] - par->ShankLen*z[69]*z[262] - par->ThighLen*z[29]*z[263] - 
  par->ThighLen*z[30]*z[262] - z[233]*z[73]*z[223] - z[233]*z[75]*z[226] - 
  z[235]*z[51]*z[223] - z[235]*z[52]*z[226];
  z[471] = z[74]*z[258]*z[262] + z[76]*z[261]*z[262] + z[78]*z[258]*z[263] + 
  z[79]*z[261]*z[263] + par->ShankCMy*(z[236]*z[40]+z[237]*z[39]) - par->ShankLen*
  z[39]*z[263] - par->ShankLen*z[40]*z[262] - z[233]*z[74]*z[223] - z[233]*
  z[76]*z[226] - z[235]*z[78]*z[223] - z[235]*z[79]*z[226];
  z[472] = par->FootMass*(z[223]*z[377]-z[226]*z[378]) - z[295]*z[27]*z[33];
  z[473] = z[458]*z[34]*z[52] + z[458]*z[35]*z[51] + z[459]*z[34]*z[54] + 
  z[459]*z[35]*z[53] + z[52]*z[258]*z[262] + z[54]*z[258]*z[263] + z[77]*
  z[261]*z[262] + z[80]*z[261]*z[263] - z[233]*z[52]*z[223] - z[233]*z[77]*
  z[226] - z[235]*z[54]*z[223] - z[235]*z[80]*z[226] - par->ShankLen*z[34]*
  z[52]*z[262] - par->ShankLen*z[34]*z[54]*z[263] - par->ShankLen*z[35]*z[51]*
  z[262] - par->ShankLen*z[35]*z[53]*z[263];
  z[474] = par->FootMass*(z[223]*z[228]+z[226]*z[388]-par->ShankLen*z[34]*
  z[231]-par->ShankLen*z[35]*z[230]);
  z[475] = z[462]*(z[34]*z[226]+z[35]*z[223]);
  z[476] = z[462]*(par->FootCMx*z[34]-par->FootCMy*z[35]);
  z[477] = z[280]*z[73] + z[281]*z[51] - z[282]*z[75] - z[283]*z[52] - par->ShankLen*
  z[37]*z[263] - par->ShankLen*z[69]*z[262] - par->ThighLen*z[29]*z[263] - 
  par->ThighLen*z[30]*z[262];
  z[478] = z[280]*z[74] + z[281]*z[78] - z[282]*z[76] - z[283]*z[79] - par->ShankLen*
  z[39]*z[263] - par->ShankLen*z[40]*z[262];
  z[479] = par->FootMass*(par->FootCMx*z[378]+par->FootCMy*z[377]);
  z[480] = z[280]*z[52] + z[281]*z[54] - z[282]*z[77] - z[283]*z[80];
  z[481] = par->FootMass*(par->FootCMx*z[388]-par->FootCMy*z[228]);
  z[482] = 0.01*z[337] - 0.01*z[338] - 0.01*z[339]*q9pp - 0.01*z[340]*q1pp - 
  0.01*z[341]*q2pp - 0.01*z[342]*q3pp - 0.01*z[343]*q7pp - 0.01*z[344]*q8pp - 
  0.01*z[345]*q6pp - 0.01*z[346]*q4pp - 0.01*z[347]*q5pp;
  z[483] = 0.01*z[348] - 0.01*z[349] - 0.01*z[345]*q6pp - 0.01*z[346]*q3pp - 
  0.01*z[346]*q4pp - 0.01*z[347]*q5pp - 0.01*z[350]*q1pp - 0.01*z[351]*q2pp;
  z[484] = 0.01*z[352] - 0.01*z[355] - 0.01*z[356]*q1pp - 0.01*z[357]*q2pp - 
  0.01*z[360]*q3pp - 0.01*z[360]*q4pp - 0.01*z[361]*q6pp - 0.01*z[362]*q5pp;
  z[485] = 0.01*z[363] - 0.01*z[365] - 0.02*z[366]*q1pp - 0.01*z[367]*q2pp - 
  0.01*z[369]*q3pp - 0.01*z[369]*q4pp - 0.01*z[370]*q6pp - 0.01*z[371]*q5pp;
  z[486] = 0.01*z[372] - 0.01*z[373] - 0.01*z[339]*q9pp - 0.01*z[343]*q3pp - 
  0.01*z[343]*q7pp - 0.01*z[344]*q8pp - 0.01*z[374]*q1pp - 0.01*z[375]*q2pp;
  z[487] = 0.01*z[376] - 0.01*z[379] - 0.01*z[380]*q9pp - 0.01*z[381]*q1pp - 
  0.01*z[382]*q2pp - 0.01*z[385]*q3pp - 0.01*z[385]*q7pp - 0.01*z[386]*q8pp;
  z[488] = 0.01*z[387] - 0.01*z[389] - 0.02*z[391]*q1pp - 0.01*z[390]*q9pp - 
  0.01*z[392]*q2pp - 0.01*z[394]*q3pp - 0.01*z[394]*q7pp - 0.01*z[395]*q8pp;
  z[489] = 0.01*z[396] - 0.01*z[300] - 0.01*z[288]*q9pp - 0.01*z[293]*q3pp - 
  0.01*z[294]*q7pp - 0.01*z[296]*q8pp - 0.01*z[297]*q6pp - 0.01*z[298]*q4pp - 
  0.01*z[299]*q5pp - 0.01*z[341]*q1pp - 0.01*z[397]*q2pp;
  z[490] = 0.01*z[398] - 0.01*z[399] - 0.01*z[297]*q6pp - 0.01*z[298]*q3pp - 
  0.01*z[298]*q4pp - 0.01*z[299]*q5pp - 0.01*z[351]*q1pp - 0.01*z[400]*q2pp;
  z[491] = 0.01*z[401] - 0.01*z[402] - 0.01*z[357]*q1pp - 0.01*z[403]*q2pp - 
  0.01*z[404]*q3pp - 0.01*z[404]*q4pp - 0.01*z[405]*q6pp - 0.01*z[406]*q5pp;
  z[492] = 0.01*z[407] - 0.01*z[408] - 0.02*z[409]*q2pp - 0.01*z[367]*q1pp - 
  0.01*z[410]*q3pp - 0.01*z[410]*q4pp - 0.01*z[411]*q6pp - 0.01*z[412]*q5pp;
  z[493] = 0.01*z[413] - 0.01*z[414] - 0.01*z[288]*q9pp - 0.01*z[294]*q3pp - 
  0.01*z[294]*q7pp - 0.01*z[296]*q8pp - 0.01*z[375]*q1pp - 0.01*z[415]*q2pp;
  z[494] = 0.01*z[416] - 0.01*z[417] - 0.01*z[382]*q1pp - 0.01*z[418]*q9pp - 
  0.01*z[419]*q2pp - 0.01*z[420]*q3pp - 0.01*z[420]*q7pp - 0.01*z[421]*q8pp;
  z[495] = 0.01*z[422] - 0.01*z[423] - 0.02*z[425]*q2pp - 0.01*z[392]*q1pp - 
  0.01*z[424]*q9pp - 0.01*z[426]*q3pp - 0.01*z[426]*q7pp - 0.01*z[427]*q8pp;
  z[496] = -0.01*z[255] - 0.01*z[263];
  z[497] = 0.01*z[254] + 0.01*z[262];
  z[498] = 0.01*z[428] - 0.01*z[293]*q2pp - 0.01*z[342]*q1pp;
  z[499] = 0.01*z[429] - 0.01*z[298]*q2pp - 0.01*z[346]*q1pp;
  z[500] = 0.01*z[432] + 0.01*z[438]*q6pp - 0.01*z[433] - 0.01*z[360]*q1pp - 
  0.01*z[404]*q2pp - 0.01*z[435]*q3pp - 0.01*z[435]*q4pp - 0.01*z[437]*q5pp;
  z[501] = 0.01*z[439] - 0.01*z[440] - 0.02*z[441]*q3pp - 0.02*z[441]*q4pp - 
  0.01*z[369]*q1pp - 0.01*z[410]*q2pp - 0.01*z[442]*q5pp - 0.01*z[443]*q6pp;
  z[502] = 0.01*z[444] - 0.01*z[294]*q2pp - 0.01*z[343]*q1pp;
  z[503] = 0.01*z[445] + 0.01*z[449]*q9pp - 0.01*z[446] - 0.01*z[385]*q1pp - 
  0.01*z[420]*q2pp - 0.01*z[447]*q3pp - 0.01*z[447]*q7pp - 0.01*z[448]*q8pp;
  z[504] = 0.01*z[450] - 0.01*z[451] - 0.02*z[452]*q3pp - 0.02*z[452]*q7pp - 
  0.01*z[394]*q1pp - 0.01*z[426]*q2pp - 0.01*z[453]*q8pp - 0.01*z[454]*q9pp;
  z[505] = 0.01*z[455] - 0.01*z[299]*q2pp - 0.01*z[347]*q1pp;
  z[506] = 0.01*z[456] - 0.01*z[457] - 0.01*z[362]*q1pp - 0.01*z[406]*q2pp - 
  0.01*z[437]*q3pp - 0.01*z[437]*q4pp;
  z[507] = 0.01*z[460] + 0.01*z[464]*q6pp + 0.02*z[463]*q5pp - 0.01*z[461] - 
  0.01*z[371]*q1pp - 0.01*z[412]*q2pp - 0.01*z[442]*q3pp - 0.01*z[442]*q4pp;
  z[508] = 0.01*z[465] - 0.01*z[297]*q2pp - 0.01*z[345]*q1pp;
  z[509] = 0.01*z[466] + 0.01*z[467] + 0.01*z[438]*q3pp + 0.01*z[438]*q4pp - 
  0.01*z[361]*q1pp - 0.01*z[405]*q2pp;
  z[510] = 0.01*z[468] + 0.01*z[464]*q5pp - 0.01*z[469] - 0.01*z[370]*q1pp - 
  0.01*z[411]*q2pp - 0.01*z[443]*q3pp - 0.01*z[443]*q4pp;
  z[511] = 0.01*z[470] - 0.01*z[296]*q2pp - 0.01*z[344]*q1pp;
  z[512] = 0.01*z[471] - 0.01*z[472] - 0.01*z[386]*q1pp - 0.01*z[421]*q2pp - 
  0.01*z[448]*q3pp - 0.01*z[448]*q7pp;
  z[513] = 0.01*z[473] + 0.01*z[476]*q9pp + 0.02*z[475]*q8pp - 0.01*z[474] - 
  0.01*z[395]*q1pp - 0.01*z[427]*q2pp - 0.01*z[453]*q3pp - 0.01*z[453]*q7pp;
  z[514] = 0.01*z[477] - 0.01*z[288]*q2pp - 0.01*z[339]*q1pp;
  z[515] = 0.01*z[478] + 0.01*z[479] + 0.01*z[449]*q3pp + 0.01*z[449]*q7pp - 
  0.01*z[380]*q1pp - 0.01*z[418]*q2pp;
  z[516] = 0.01*z[480] + 0.01*z[476]*q8pp - 0.01*z[481] - 0.01*z[390]*q1pp - 
  0.01*z[424]*q2pp - 0.01*z[454]*q3pp - 0.01*z[454]*q7pp;
  z[517] = par->airdrag*(z[1]*(2*par->wind*z[1]*z[242]-z[245]-pow(z[242],2)-
  pow(z[243],2)-2*par->wind*z[2]*z[243])+(par->TrunkCMy*q3p-z[1]*q1p-z[2]*q2p)*(
  z[1]*z[242]-par->wind*pow(z[1],2)-par->wind*pow(z[2],2)-z[2]*z[243]))/pow((
  z[245]+pow(z[242],2)+pow(z[243],2)+2*par->wind*z[2]*z[243]-2*par->wind*z[1]*
  z[242]),0.5);
  z[518] = par->airdrag*(z[2]*(2*par->wind*z[1]*z[242]-z[245]-pow(z[242],2)-
  pow(z[243],2)-2*par->wind*z[2]*z[243])+(z[1]*q2p-z[2]*q1p)*(z[1]*z[242]-
  par->wind*pow(z[1],2)-par->wind*pow(z[2],2)-z[2]*z[243]))/pow((z[245]+pow(
  z[242],2)+pow(z[243],2)+2*par->wind*z[2]*z[243]-2*par->wind*z[1]*z[242]),
  0.5);
  z[519] = z[244]*(z[1]*z[242]-par->wind*pow(z[1],2)-par->wind*pow(z[2],2)-
  z[2]*z[243])/pow((z[245]+pow(z[242],2)+pow(z[243],2)+2*par->wind*z[2]*
  z[243]-2*par->wind*z[1]*z[242]),0.5);
  z[520] = z[1]*z[517] + z[2]*z[518] + pow(z[1],2)*z[519] + pow(z[2],2)*
  z[519];
  z[521] = par->airdrag*((par->TrunkCMy*q3p-z[1]*q1p-z[2]*q2p)*(z[1]*z[243]+
  z[2]*z[242])+z[2]*(2*par->wind*z[1]*z[242]-z[245]-pow(z[242],2)-pow(z[243],
  2)-2*par->wind*z[2]*z[243]))/pow((z[245]+pow(z[242],2)+pow(z[243],2)+2*
  par->wind*z[2]*z[243]-2*par->wind*z[1]*z[242]),0.5);
  z[522] = par->airdrag*((z[1]*q2p-z[2]*q1p)*(z[1]*z[243]+z[2]*z[242])-z[1]*(
  2*par->wind*z[1]*z[242]-z[245]-pow(z[242],2)-pow(z[243],2)-2*par->wind*z[2]*
  z[243]))/pow((z[245]+pow(z[242],2)+pow(z[243],2)+2*par->wind*z[2]*z[243]-2*
  par->wind*z[1]*z[242]),0.5);
  z[523] = z[244]*(z[1]*z[243]+z[2]*z[242])/pow((z[245]+pow(z[242],2)+pow(
  z[243],2)+2*par->wind*z[2]*z[243]-2*par->wind*z[1]*z[242]),0.5);
  z[524] = z[1]*z[521] + z[2]*z[522] + pow(z[1],2)*z[523] + pow(z[2],2)*
  z[523];
  z[525] = par->airdrag*par->TrunkCMy;
  z[526] = z[525]*(2*par->wind*z[1]*z[242]-z[245]-pow(z[242],2)-pow(z[243],2)-
  2*par->wind*z[2]*z[243]-(par->TrunkCMy*q3p-z[1]*q1p-z[2]*q2p)*(par->wind*
  z[1]-z[242]))/pow((z[245]+pow(z[242],2)+pow(z[243],2)+2*par->wind*z[2]*
  z[243]-2*par->wind*z[1]*z[242]),0.5);
  z[527] = z[525]*(z[1]*q2p-z[2]*q1p)*(par->wind*z[1]-z[242])/pow((z[245]+
  pow(z[242],2)+pow(z[243],2)+2*par->wind*z[2]*z[243]-2*par->wind*z[1]*z[242]),
  0.5);
  z[528] = par->TrunkCMy*z[244];
  z[529] = z[528]*(par->wind*z[1]-z[242])/pow((z[245]+pow(z[242],2)+pow(
  z[243],2)+2*par->wind*z[2]*z[243]-2*par->wind*z[1]*z[242]),0.5);
  z[530] = z[2]*z[527] + pow(z[1],2)*z[529] + pow(z[2],2)*z[529] - z[1]*
  z[526];
  z[531] = par->ThighLen*(q3p+q4p+z[10]);
  z[532] = par->ShankLen*(q3p+q4p+q5p) + par->ShankLen*z[23] + z[5]*z[531];
  z[533] = z[13]*z[532] + z[6]*z[12]*z[531];
  z[534] = z[533] - par->FootCMx*(q3p+q4p+q5p+q6p) - par->FootCMx*z[213];
  z[535] = z[12]*z[532] - z[6]*z[13]*z[531];
  z[536] = z[535] - par->FootCMy*(q3p+q4p+q5p+q6p) - par->FootCMy*z[213];
  z[537] = par->ThighLen*(q3p+q7p+z[32]);
  z[538] = par->ShankLen*(q3p+q7p+q8p) + par->ShankLen*z[45] + z[27]*z[537];
  z[539] = z[35]*z[538] + z[28]*z[34]*z[537];
  z[540] = z[539] - par->FootCMx*(q3p+q7p+q8p+q9p) - par->FootCMx*z[229];
  z[541] = z[34]*z[538] - z[28]*z[35]*z[537];
  z[542] = z[541] - par->FootCMy*(q3p+q7p+q8p+q9p) - par->FootCMy*z[229];
  z[543] = z[5]*z[531] - par->ShankCMy*(q3p+q4p+q5p) - par->ShankCMy*z[23];
  z[544] = z[27]*z[537] - par->ShankCMy*(q3p+q7p+q8p) - par->ShankCMy*z[45];
  z[545] = par->ThighCMy*(q3p+q4p+z[10]);
  z[546] = par->ThighCMy*(q3p+q7p+z[32]);
  z[547] = 2*z[292]*z[2]*q3p + par->FootMass*(z[47]*z[534]+z[48]*z[536]) + 
  par->FootMass*(z[51]*z[540]+z[52]*z[542]) + par->ShankMass*(z[18]*z[543]+
  z[6]*z[15]*z[531]) + par->ShankMass*(z[40]*z[544]+z[28]*z[37]*z[537]) - 
  par->ThighMass*z[8]*z[545] - par->ThighMass*z[30]*z[546];
  z[548] = par->FootMass*(z[47]*z[534]+z[48]*z[536]) + par->ShankMass*(z[18]*
  z[543]+z[6]*z[15]*z[531]) - par->ThighMass*z[8]*z[545];
  z[549] = par->ShankLen*(q3p+q4p+q5p+z[23]);
  z[550] = z[13]*z[549] - par->FootCMx*(q3p+q4p+q5p+q6p) - par->FootCMx*
  z[213];
  z[551] = z[12]*z[549] - par->FootCMy*(q3p+q4p+q5p+q6p) - par->FootCMy*
  z[213];
  z[552] = par->ShankCMy*(q3p+q4p+q5p+z[23]);
  z[553] = par->FootMass*(z[47]*z[550]+z[48]*z[551]) - par->ShankMass*z[18]*
  z[552];
  z[554] = par->FootCMx*(q3p+q4p+q5p+q6p+z[213]);
  z[555] = par->FootCMy*(q3p+q4p+q5p+q6p+z[213]);
  z[556] = par->FootMass*(z[47]*z[554]+z[48]*z[555]);
  z[557] = par->FootMass*(z[51]*z[540]+z[52]*z[542]) + par->ShankMass*(z[40]*
  z[544]+z[28]*z[37]*z[537]) - par->ThighMass*z[30]*z[546];
  z[558] = par->ShankLen*(q3p+q7p+q8p+z[45]);
  z[559] = z[35]*z[558] - par->FootCMx*(q3p+q7p+q8p+q9p) - par->FootCMx*
  z[229];
  z[560] = z[34]*z[558] - par->FootCMy*(q3p+q7p+q8p+q9p) - par->FootCMy*
  z[229];
  z[561] = par->ShankCMy*(q3p+q7p+q8p+z[45]);
  z[562] = par->FootMass*(z[51]*z[559]+z[52]*z[560]) - par->ShankMass*z[40]*
  z[561];
  z[563] = par->FootCMx*(q3p+q7p+q8p+q9p+z[229]);
  z[564] = par->FootCMy*(q3p+q7p+q8p+q9p+z[229]);
  z[565] = par->FootMass*(z[51]*z[563]+z[52]*z[564]);
  z[566] = z[2]*z[517] - z[1]*z[518];
  z[567] = z[2]*z[521] - z[1]*z[522];
  z[568] = -z[1]*z[527] - z[2]*z[526];
  z[569] = par->FootMass*(z[49]*z[534]+z[50]*z[536]) + par->FootMass*(z[53]*
  z[540]+z[54]*z[542]) + par->ShankMass*(z[17]*z[543]+z[6]*z[14]*z[531]) + 
  par->ShankMass*(z[39]*z[544]+z[28]*z[36]*z[537]) - 2*z[292]*z[1]*q3p - 
  par->ThighMass*z[7]*z[545] - par->ThighMass*z[29]*z[546];
  z[570] = par->FootMass*(z[49]*z[534]+z[50]*z[536]) + par->ShankMass*(z[17]*
  z[543]+z[6]*z[14]*z[531]) - par->ThighMass*z[7]*z[545];
  z[571] = par->FootMass*(z[49]*z[550]+z[50]*z[551]) - par->ShankMass*z[17]*
  z[552];
  z[572] = par->FootMass*(z[49]*z[554]+z[50]*z[555]);
  z[573] = par->FootMass*(z[53]*z[540]+z[54]*z[542]) + par->ShankMass*(z[39]*
  z[544]+z[28]*z[36]*z[537]) - par->ThighMass*z[29]*z[546];
  z[574] = par->FootMass*(z[53]*z[559]+z[54]*z[560]) - par->ShankMass*z[39]*
  z[561];
  z[575] = par->FootMass*(z[53]*z[563]+z[54]*z[564]);
  z[576] = par->TrunkCMy*(z[517]+z[1]*z[519]);
  z[577] = par->TrunkCMy*(z[521]+z[1]*z[523]);
  z[578] = par->TrunkCMy*(z[526]-z[1]*z[529]);
  z[579] = par->FootMass*(z[208]*z[534]+z[209]*z[536]) + par->FootMass*(
  z[224]*z[540]+z[225]*z[542]) - par->ShankMass*(z[19]*z[543]-z[6]*z[201]*
  z[531]) - par->ShankMass*(z[41]*z[544]-z[28]*z[217]*z[537]);
  z[580] = par->FootMass*(z[208]*z[534]+z[209]*z[536]) - par->ShankMass*(
  z[19]*z[543]-z[6]*z[201]*z[531]);
  z[581] = par->ShankMass*z[19]*z[552] + par->FootMass*(z[208]*z[550]+z[209]*
  z[551]);
  z[582] = par->FootMass*(z[208]*z[554]+z[209]*z[555]);
  z[583] = par->FootMass*(z[224]*z[540]+z[225]*z[542]) - par->ShankMass*(
  z[41]*z[544]-z[28]*z[217]*z[537]);
  z[584] = par->ShankMass*z[41]*z[561] + par->FootMass*(z[224]*z[559]+z[225]*
  z[560]);
  z[585] = par->FootMass*(z[224]*z[563]+z[225]*z[564]);
  z[586] = par->FootMass*(z[207]*z[534]+z[210]*z[536]) - z[295]*z[6]*z[531];
  z[587] = par->FootMass*(z[207]*z[550]+z[210]*z[551]);
  z[588] = par->FootMass*(z[207]*z[554]+z[210]*z[555]);
  z[589] = par->FootMass*(par->FootCMx*z[536]-par->FootCMy*z[534]);
  z[590] = par->FootMass*(par->FootCMx*z[551]-par->FootCMy*z[550]);
  z[591] = par->FootMass*(par->FootCMx*z[555]-par->FootCMy*z[554]);
  z[592] = par->FootMass*(z[223]*z[540]+z[226]*z[542]) - z[295]*z[28]*z[537];
  z[593] = par->FootMass*(z[223]*z[559]+z[226]*z[560]);
  z[594] = par->FootMass*(z[223]*z[563]+z[226]*z[564]);
  z[595] = par->FootMass*(par->FootCMx*z[542]-par->FootCMy*z[540]);
  z[596] = par->FootMass*(par->FootCMx*z[560]-par->FootCMy*z[559]);
  z[597] = par->FootMass*(par->FootCMx*z[564]-par->FootCMy*z[563]);
  z[598] = 0.01*z[530] - 0.01*z[547];
  z[599] = 0.01*z[568] - 0.01*z[569];
  z[600] = 0.01*z[578] - 0.01*z[579];
  z[601] = par->bodyweight*(z[47]*z[49]+z[48]*z[50]);
  z[602] = par->bodyweight*(z[51]*z[53]+z[52]*z[54]);
  z[603] = par->bodyweight*(par->ShankLen*z[15]+par->ThighLen*z[7]-q2-z[47]*
  z[251]-z[48]*z[252]);
  z[604] = par->bodyweight*(q1+par->ShankLen*z[14]+par->ThighLen*z[9]-z[49]*
  z[251]-z[50]*z[252]);
  z[605] = par->bodyweight*(par->ShankLen*z[37]+par->ThighLen*z[29]-q2-z[51]*
  z[259]-z[52]*z[260]);
  z[606] = par->bodyweight*(q1+par->ShankLen*z[36]+par->ThighLen*z[31]-z[53]*
  z[259]-z[54]*z[260]);
  z[607] = par->bodyweight*(par->ShankLen*z[15]+par->ThighLen*z[7]-q2-z[47]*
  z[250]-z[48]*z[253]);
  z[608] = par->bodyweight*(q1+par->ShankLen*z[14]+par->ThighLen*z[9]-z[49]*
  z[250]-z[50]*z[253]);
  z[609] = par->bodyweight*(q2-par->ShankLen*z[15]-par->ThighLen*z[7]);
  z[610] = par->bodyweight*(q1+par->ShankLen*z[14]+par->ThighLen*z[9]);
  z[611] = par->bodyweight*(par->ShankLen*z[37]+par->ThighLen*z[29]-q2-z[51]*
  z[258]-z[52]*z[261]);
  z[612] = par->bodyweight*(q1+par->ShankLen*z[36]+par->ThighLen*z[31]-z[53]*
  z[258]-z[54]*z[261]);
  z[613] = par->bodyweight*(q2-par->ShankLen*z[37]-par->ThighLen*z[29]);
  z[614] = par->bodyweight*(q1+par->ShankLen*z[36]+par->ThighLen*z[31]);
  z[615] = par->bodyweight*(pow(z[47],2)+pow(z[48],2));
  z[616] = par->bodyweight*(pow(z[51],2)+pow(z[52],2));
  z[617] = par->bodyweight*(pow(z[49],2)+pow(z[50],2));
  z[618] = par->bodyweight*(pow(z[53],2)+pow(z[54],2));


  fk[0] = q1;
  fk[1] = q2;
  fk[2] = z[1];
  fk[3] = -z[2];
  fk[4] = z[2];
  fk[5] = z[1];
  fk[6] = q1;
  fk[7] = q2;
  fk[8] = z[7];
  fk[9] = z[8];
  fk[10] = z[9];
  fk[11] = z[7];
  fk[12] = q1 - par->ThighLen*z[8];
  fk[13] = q2 - par->ThighLen*z[7];
  fk[14] = z[15];
  fk[15] = z[18];
  fk[16] = z[14];
  fk[17] = z[17];
  fk[18] = q1 - par->ShankLen*z[18] - par->ThighLen*z[8];
  fk[19] = q2 - par->ShankLen*z[17] - par->ThighLen*z[7];
  fk[20] = z[47];
  fk[21] = z[48];
  fk[22] = z[49];
  fk[23] = z[50];
  fk[24] = q1;
  fk[25] = q2;
  fk[26] = z[29];
  fk[27] = z[30];
  fk[28] = z[31];
  fk[29] = z[29];
  fk[30] = q1 - par->ThighLen*z[30];
  fk[31] = q2 - par->ThighLen*z[29];
  fk[32] = z[37];
  fk[33] = z[40];
  fk[34] = z[36];
  fk[35] = z[39];
  fk[36] = q1 - par->ShankLen*z[40] - par->ThighLen*z[30];
  fk[37] = q2 - par->ShankLen*z[39] - par->ThighLen*z[29];
  fk[38] = z[51];
  fk[39] = z[52];
  fk[40] = z[53];
  fk[41] = z[54];
  dfk_dq[0][0] = 1;
  dfk_dq[0][1] = 0;
  dfk_dq[0][2] = 0;
  dfk_dq[0][3] = 0;
  dfk_dq[0][4] = 0;
  dfk_dq[0][5] = 0;
  dfk_dq[0][6] = 0;
  dfk_dq[0][7] = 0;
  dfk_dq[0][8] = 0;
  dfk_dq[1][0] = 0;
  dfk_dq[1][1] = 1;
  dfk_dq[1][2] = 0;
  dfk_dq[1][3] = 0;
  dfk_dq[1][4] = 0;
  dfk_dq[1][5] = 0;
  dfk_dq[1][6] = 0;
  dfk_dq[1][7] = 0;
  dfk_dq[1][8] = 0;
  dfk_dq[2][0] = 0;
  dfk_dq[2][1] = 0;
  dfk_dq[2][2] = -z[2];
  dfk_dq[2][3] = 0;
  dfk_dq[2][4] = 0;
  dfk_dq[2][5] = 0;
  dfk_dq[2][6] = 0;
  dfk_dq[2][7] = 0;
  dfk_dq[2][8] = 0;
  dfk_dq[3][0] = 0;
  dfk_dq[3][1] = 0;
  dfk_dq[3][2] = -z[1];
  dfk_dq[3][3] = 0;
  dfk_dq[3][4] = 0;
  dfk_dq[3][5] = 0;
  dfk_dq[3][6] = 0;
  dfk_dq[3][7] = 0;
  dfk_dq[3][8] = 0;
  dfk_dq[4][0] = 0;
  dfk_dq[4][1] = 0;
  dfk_dq[4][2] = z[1];
  dfk_dq[4][3] = 0;
  dfk_dq[4][4] = 0;
  dfk_dq[4][5] = 0;
  dfk_dq[4][6] = 0;
  dfk_dq[4][7] = 0;
  dfk_dq[4][8] = 0;
  dfk_dq[5][0] = 0;
  dfk_dq[5][1] = 0;
  dfk_dq[5][2] = -z[2];
  dfk_dq[5][3] = 0;
  dfk_dq[5][4] = 0;
  dfk_dq[5][5] = 0;
  dfk_dq[5][6] = 0;
  dfk_dq[5][7] = 0;
  dfk_dq[5][8] = 0;
  dfk_dq[6][0] = 1;
  dfk_dq[6][1] = 0;
  dfk_dq[6][2] = 0;
  dfk_dq[6][3] = 0;
  dfk_dq[6][4] = 0;
  dfk_dq[6][5] = 0;
  dfk_dq[6][6] = 0;
  dfk_dq[6][7] = 0;
  dfk_dq[6][8] = 0;
  dfk_dq[7][0] = 0;
  dfk_dq[7][1] = 1;
  dfk_dq[7][2] = 0;
  dfk_dq[7][3] = 0;
  dfk_dq[7][4] = 0;
  dfk_dq[7][5] = 0;
  dfk_dq[7][6] = 0;
  dfk_dq[7][7] = 0;
  dfk_dq[7][8] = 0;
  dfk_dq[8][0] = 0;
  dfk_dq[8][1] = 0;
  dfk_dq[8][2] = z[8];
  dfk_dq[8][3] = z[8];
  dfk_dq[8][4] = 0;
  dfk_dq[8][5] = 0;
  dfk_dq[8][6] = 0;
  dfk_dq[8][7] = 0;
  dfk_dq[8][8] = 0;
  dfk_dq[9][0] = 0;
  dfk_dq[9][1] = 0;
  dfk_dq[9][2] = z[55];
  dfk_dq[9][3] = z[55];
  dfk_dq[9][4] = 0;
  dfk_dq[9][5] = 0;
  dfk_dq[9][6] = 0;
  dfk_dq[9][7] = 0;
  dfk_dq[9][8] = 0;
  dfk_dq[10][0] = 0;
  dfk_dq[10][1] = 0;
  dfk_dq[10][2] = z[7];
  dfk_dq[10][3] = z[7];
  dfk_dq[10][4] = 0;
  dfk_dq[10][5] = 0;
  dfk_dq[10][6] = 0;
  dfk_dq[10][7] = 0;
  dfk_dq[10][8] = 0;
  dfk_dq[11][0] = 0;
  dfk_dq[11][1] = 0;
  dfk_dq[11][2] = z[8];
  dfk_dq[11][3] = z[8];
  dfk_dq[11][4] = 0;
  dfk_dq[11][5] = 0;
  dfk_dq[11][6] = 0;
  dfk_dq[11][7] = 0;
  dfk_dq[11][8] = 0;
  dfk_dq[12][0] = 1;
  dfk_dq[12][1] = 0;
  dfk_dq[12][2] = -z[81];
  dfk_dq[12][3] = -z[81];
  dfk_dq[12][4] = 0;
  dfk_dq[12][5] = 0;
  dfk_dq[12][6] = 0;
  dfk_dq[12][7] = 0;
  dfk_dq[12][8] = 0;
  dfk_dq[13][0] = 0;
  dfk_dq[13][1] = 1;
  dfk_dq[13][2] = -z[82];
  dfk_dq[13][3] = -z[82];
  dfk_dq[13][4] = 0;
  dfk_dq[13][5] = 0;
  dfk_dq[13][6] = 0;
  dfk_dq[13][7] = 0;
  dfk_dq[13][8] = 0;
  dfk_dq[14][0] = 0;
  dfk_dq[14][1] = 0;
  dfk_dq[14][2] = z[56];
  dfk_dq[14][3] = z[56];
  dfk_dq[14][4] = z[18];
  dfk_dq[14][5] = 0;
  dfk_dq[14][6] = 0;
  dfk_dq[14][7] = 0;
  dfk_dq[14][8] = 0;
  dfk_dq[15][0] = 0;
  dfk_dq[15][1] = 0;
  dfk_dq[15][2] = z[57];
  dfk_dq[15][3] = z[57];
  dfk_dq[15][4] = z[58];
  dfk_dq[15][5] = 0;
  dfk_dq[15][6] = 0;
  dfk_dq[15][7] = 0;
  dfk_dq[15][8] = 0;
  dfk_dq[16][0] = 0;
  dfk_dq[16][1] = 0;
  dfk_dq[16][2] = z[15];
  dfk_dq[16][3] = z[15];
  dfk_dq[16][4] = z[17];
  dfk_dq[16][5] = 0;
  dfk_dq[16][6] = 0;
  dfk_dq[16][7] = 0;
  dfk_dq[16][8] = 0;
  dfk_dq[17][0] = 0;
  dfk_dq[17][1] = 0;
  dfk_dq[17][2] = z[18];
  dfk_dq[17][3] = z[18];
  dfk_dq[17][4] = z[59];
  dfk_dq[17][5] = 0;
  dfk_dq[17][6] = 0;
  dfk_dq[17][7] = 0;
  dfk_dq[17][8] = 0;
  dfk_dq[18][0] = 1;
  dfk_dq[18][1] = 0;
  dfk_dq[18][2] = z[83];
  dfk_dq[18][3] = z[83];
  dfk_dq[18][4] = -z[84];
  dfk_dq[18][5] = 0;
  dfk_dq[18][6] = 0;
  dfk_dq[18][7] = 0;
  dfk_dq[18][8] = 0;
  dfk_dq[19][0] = 0;
  dfk_dq[19][1] = 1;
  dfk_dq[19][2] = z[85];
  dfk_dq[19][3] = z[85];
  dfk_dq[19][4] = -z[86];
  dfk_dq[19][5] = 0;
  dfk_dq[19][6] = 0;
  dfk_dq[19][7] = 0;
  dfk_dq[19][8] = 0;
  dfk_dq[20][0] = 0;
  dfk_dq[20][1] = 0;
  dfk_dq[20][2] = z[60];
  dfk_dq[20][3] = z[60];
  dfk_dq[20][4] = z[61];
  dfk_dq[20][5] = z[48];
  dfk_dq[20][6] = 0;
  dfk_dq[20][7] = 0;
  dfk_dq[20][8] = 0;
  dfk_dq[21][0] = 0;
  dfk_dq[21][1] = 0;
  dfk_dq[21][2] = z[62];
  dfk_dq[21][3] = z[62];
  dfk_dq[21][4] = z[63];
  dfk_dq[21][5] = z[64];
  dfk_dq[21][6] = 0;
  dfk_dq[21][7] = 0;
  dfk_dq[21][8] = 0;
  dfk_dq[22][0] = 0;
  dfk_dq[22][1] = 0;
  dfk_dq[22][2] = z[47];
  dfk_dq[22][3] = z[47];
  dfk_dq[22][4] = z[65];
  dfk_dq[22][5] = z[50];
  dfk_dq[22][6] = 0;
  dfk_dq[22][7] = 0;
  dfk_dq[22][8] = 0;
  dfk_dq[23][0] = 0;
  dfk_dq[23][1] = 0;
  dfk_dq[23][2] = z[48];
  dfk_dq[23][3] = z[48];
  dfk_dq[23][4] = z[66];
  dfk_dq[23][5] = z[67];
  dfk_dq[23][6] = 0;
  dfk_dq[23][7] = 0;
  dfk_dq[23][8] = 0;
  dfk_dq[24][0] = 1;
  dfk_dq[24][1] = 0;
  dfk_dq[24][2] = 0;
  dfk_dq[24][3] = 0;
  dfk_dq[24][4] = 0;
  dfk_dq[24][5] = 0;
  dfk_dq[24][6] = 0;
  dfk_dq[24][7] = 0;
  dfk_dq[24][8] = 0;
  dfk_dq[25][0] = 0;
  dfk_dq[25][1] = 1;
  dfk_dq[25][2] = 0;
  dfk_dq[25][3] = 0;
  dfk_dq[25][4] = 0;
  dfk_dq[25][5] = 0;
  dfk_dq[25][6] = 0;
  dfk_dq[25][7] = 0;
  dfk_dq[25][8] = 0;
  dfk_dq[26][0] = 0;
  dfk_dq[26][1] = 0;
  dfk_dq[26][2] = z[30];
  dfk_dq[26][3] = 0;
  dfk_dq[26][4] = 0;
  dfk_dq[26][5] = 0;
  dfk_dq[26][6] = z[30];
  dfk_dq[26][7] = 0;
  dfk_dq[26][8] = 0;
  dfk_dq[27][0] = 0;
  dfk_dq[27][1] = 0;
  dfk_dq[27][2] = z[68];
  dfk_dq[27][3] = 0;
  dfk_dq[27][4] = 0;
  dfk_dq[27][5] = 0;
  dfk_dq[27][6] = z[68];
  dfk_dq[27][7] = 0;
  dfk_dq[27][8] = 0;
  dfk_dq[28][0] = 0;
  dfk_dq[28][1] = 0;
  dfk_dq[28][2] = z[29];
  dfk_dq[28][3] = 0;
  dfk_dq[28][4] = 0;
  dfk_dq[28][5] = 0;
  dfk_dq[28][6] = z[29];
  dfk_dq[28][7] = 0;
  dfk_dq[28][8] = 0;
  dfk_dq[29][0] = 0;
  dfk_dq[29][1] = 0;
  dfk_dq[29][2] = z[30];
  dfk_dq[29][3] = 0;
  dfk_dq[29][4] = 0;
  dfk_dq[29][5] = 0;
  dfk_dq[29][6] = z[30];
  dfk_dq[29][7] = 0;
  dfk_dq[29][8] = 0;
  dfk_dq[30][0] = 1;
  dfk_dq[30][1] = 0;
  dfk_dq[30][2] = -z[87];
  dfk_dq[30][3] = 0;
  dfk_dq[30][4] = 0;
  dfk_dq[30][5] = 0;
  dfk_dq[30][6] = -z[87];
  dfk_dq[30][7] = 0;
  dfk_dq[30][8] = 0;
  dfk_dq[31][0] = 0;
  dfk_dq[31][1] = 1;
  dfk_dq[31][2] = -z[88];
  dfk_dq[31][3] = 0;
  dfk_dq[31][4] = 0;
  dfk_dq[31][5] = 0;
  dfk_dq[31][6] = -z[88];
  dfk_dq[31][7] = 0;
  dfk_dq[31][8] = 0;
  dfk_dq[32][0] = 0;
  dfk_dq[32][1] = 0;
  dfk_dq[32][2] = z[69];
  dfk_dq[32][3] = 0;
  dfk_dq[32][4] = 0;
  dfk_dq[32][5] = 0;
  dfk_dq[32][6] = z[69];
  dfk_dq[32][7] = z[40];
  dfk_dq[32][8] = 0;
  dfk_dq[33][0] = 0;
  dfk_dq[33][1] = 0;
  dfk_dq[33][2] = z[70];
  dfk_dq[33][3] = 0;
  dfk_dq[33][4] = 0;
  dfk_dq[33][5] = 0;
  dfk_dq[33][6] = z[70];
  dfk_dq[33][7] = z[71];
  dfk_dq[33][8] = 0;
  dfk_dq[34][0] = 0;
  dfk_dq[34][1] = 0;
  dfk_dq[34][2] = z[37];
  dfk_dq[34][3] = 0;
  dfk_dq[34][4] = 0;
  dfk_dq[34][5] = 0;
  dfk_dq[34][6] = z[37];
  dfk_dq[34][7] = z[39];
  dfk_dq[34][8] = 0;
  dfk_dq[35][0] = 0;
  dfk_dq[35][1] = 0;
  dfk_dq[35][2] = z[40];
  dfk_dq[35][3] = 0;
  dfk_dq[35][4] = 0;
  dfk_dq[35][5] = 0;
  dfk_dq[35][6] = z[40];
  dfk_dq[35][7] = z[72];
  dfk_dq[35][8] = 0;
  dfk_dq[36][0] = 1;
  dfk_dq[36][1] = 0;
  dfk_dq[36][2] = z[89];
  dfk_dq[36][3] = 0;
  dfk_dq[36][4] = 0;
  dfk_dq[36][5] = 0;
  dfk_dq[36][6] = z[89];
  dfk_dq[36][7] = -z[90];
  dfk_dq[36][8] = 0;
  dfk_dq[37][0] = 0;
  dfk_dq[37][1] = 1;
  dfk_dq[37][2] = z[91];
  dfk_dq[37][3] = 0;
  dfk_dq[37][4] = 0;
  dfk_dq[37][5] = 0;
  dfk_dq[37][6] = z[91];
  dfk_dq[37][7] = -z[92];
  dfk_dq[37][8] = 0;
  dfk_dq[38][0] = 0;
  dfk_dq[38][1] = 0;
  dfk_dq[38][2] = z[73];
  dfk_dq[38][3] = 0;
  dfk_dq[38][4] = 0;
  dfk_dq[38][5] = 0;
  dfk_dq[38][6] = z[73];
  dfk_dq[38][7] = z[74];
  dfk_dq[38][8] = z[52];
  dfk_dq[39][0] = 0;
  dfk_dq[39][1] = 0;
  dfk_dq[39][2] = z[75];
  dfk_dq[39][3] = 0;
  dfk_dq[39][4] = 0;
  dfk_dq[39][5] = 0;
  dfk_dq[39][6] = z[75];
  dfk_dq[39][7] = z[76];
  dfk_dq[39][8] = z[77];
  dfk_dq[40][0] = 0;
  dfk_dq[40][1] = 0;
  dfk_dq[40][2] = z[51];
  dfk_dq[40][3] = 0;
  dfk_dq[40][4] = 0;
  dfk_dq[40][5] = 0;
  dfk_dq[40][6] = z[51];
  dfk_dq[40][7] = z[78];
  dfk_dq[40][8] = z[54];
  dfk_dq[41][0] = 0;
  dfk_dq[41][1] = 0;
  dfk_dq[41][2] = z[52];
  dfk_dq[41][3] = 0;
  dfk_dq[41][4] = 0;
  dfk_dq[41][5] = 0;
  dfk_dq[41][6] = z[52];
  dfk_dq[41][7] = z[79];
  dfk_dq[41][8] = z[80];
  fkdot[0] = q1p;
  fkdot[1] = q2p;
  fkdot[2] = -z[93];
  fkdot[3] = -z[94];
  fkdot[4] = z[94];
  fkdot[5] = -z[93];
  fkdot[6] = q1p;
  fkdot[7] = q2p;
  fkdot[8] = z[95];
  fkdot[9] = z[96];
  fkdot[10] = z[97];
  fkdot[11] = z[95];
  fkdot[12] = z[98];
  fkdot[13] = z[99];
  fkdot[14] = z[100];
  fkdot[15] = z[101];
  fkdot[16] = z[102];
  fkdot[17] = z[103];
  fkdot[18] = z[104];
  fkdot[19] = z[105];
  fkdot[20] = z[106];
  fkdot[21] = z[107];
  fkdot[22] = z[108];
  fkdot[23] = z[109];
  fkdot[24] = q1p;
  fkdot[25] = q2p;
  fkdot[26] = z[110];
  fkdot[27] = z[111];
  fkdot[28] = z[112];
  fkdot[29] = z[110];
  fkdot[30] = z[113];
  fkdot[31] = z[114];
  fkdot[32] = z[115];
  fkdot[33] = z[116];
  fkdot[34] = z[117];
  fkdot[35] = z[118];
  fkdot[36] = z[119];
  fkdot[37] = z[120];
  fkdot[38] = z[121];
  fkdot[39] = z[122];
  fkdot[40] = z[123];
  fkdot[41] = z[124];
  dfkdot_dq[0][0] = 0;
  dfkdot_dq[0][1] = 0;
  dfkdot_dq[0][2] = 0;
  dfkdot_dq[0][3] = 0;
  dfkdot_dq[0][4] = 0;
  dfkdot_dq[0][5] = 0;
  dfkdot_dq[0][6] = 0;
  dfkdot_dq[0][7] = 0;
  dfkdot_dq[0][8] = 0;
  dfkdot_dq[1][0] = 0;
  dfkdot_dq[1][1] = 0;
  dfkdot_dq[1][2] = 0;
  dfkdot_dq[1][3] = 0;
  dfkdot_dq[1][4] = 0;
  dfkdot_dq[1][5] = 0;
  dfkdot_dq[1][6] = 0;
  dfkdot_dq[1][7] = 0;
  dfkdot_dq[1][8] = 0;
  dfkdot_dq[2][0] = 0;
  dfkdot_dq[2][1] = 0;
  dfkdot_dq[2][2] = -z[94];
  dfkdot_dq[2][3] = 0;
  dfkdot_dq[2][4] = 0;
  dfkdot_dq[2][5] = 0;
  dfkdot_dq[2][6] = 0;
  dfkdot_dq[2][7] = 0;
  dfkdot_dq[2][8] = 0;
  dfkdot_dq[3][0] = 0;
  dfkdot_dq[3][1] = 0;
  dfkdot_dq[3][2] = z[93];
  dfkdot_dq[3][3] = 0;
  dfkdot_dq[3][4] = 0;
  dfkdot_dq[3][5] = 0;
  dfkdot_dq[3][6] = 0;
  dfkdot_dq[3][7] = 0;
  dfkdot_dq[3][8] = 0;
  dfkdot_dq[4][0] = 0;
  dfkdot_dq[4][1] = 0;
  dfkdot_dq[4][2] = -z[93];
  dfkdot_dq[4][3] = 0;
  dfkdot_dq[4][4] = 0;
  dfkdot_dq[4][5] = 0;
  dfkdot_dq[4][6] = 0;
  dfkdot_dq[4][7] = 0;
  dfkdot_dq[4][8] = 0;
  dfkdot_dq[5][0] = 0;
  dfkdot_dq[5][1] = 0;
  dfkdot_dq[5][2] = -z[94];
  dfkdot_dq[5][3] = 0;
  dfkdot_dq[5][4] = 0;
  dfkdot_dq[5][5] = 0;
  dfkdot_dq[5][6] = 0;
  dfkdot_dq[5][7] = 0;
  dfkdot_dq[5][8] = 0;
  dfkdot_dq[6][0] = 0;
  dfkdot_dq[6][1] = 0;
  dfkdot_dq[6][2] = 0;
  dfkdot_dq[6][3] = 0;
  dfkdot_dq[6][4] = 0;
  dfkdot_dq[6][5] = 0;
  dfkdot_dq[6][6] = 0;
  dfkdot_dq[6][7] = 0;
  dfkdot_dq[6][8] = 0;
  dfkdot_dq[7][0] = 0;
  dfkdot_dq[7][1] = 0;
  dfkdot_dq[7][2] = 0;
  dfkdot_dq[7][3] = 0;
  dfkdot_dq[7][4] = 0;
  dfkdot_dq[7][5] = 0;
  dfkdot_dq[7][6] = 0;
  dfkdot_dq[7][7] = 0;
  dfkdot_dq[7][8] = 0;
  dfkdot_dq[8][0] = 0;
  dfkdot_dq[8][1] = 0;
  dfkdot_dq[8][2] = z[96];
  dfkdot_dq[8][3] = z[96];
  dfkdot_dq[8][4] = 0;
  dfkdot_dq[8][5] = 0;
  dfkdot_dq[8][6] = 0;
  dfkdot_dq[8][7] = 0;
  dfkdot_dq[8][8] = 0;
  dfkdot_dq[9][0] = 0;
  dfkdot_dq[9][1] = 0;
  dfkdot_dq[9][2] = z[197];
  dfkdot_dq[9][3] = z[197];
  dfkdot_dq[9][4] = 0;
  dfkdot_dq[9][5] = 0;
  dfkdot_dq[9][6] = 0;
  dfkdot_dq[9][7] = 0;
  dfkdot_dq[9][8] = 0;
  dfkdot_dq[10][0] = 0;
  dfkdot_dq[10][1] = 0;
  dfkdot_dq[10][2] = z[95];
  dfkdot_dq[10][3] = z[95];
  dfkdot_dq[10][4] = 0;
  dfkdot_dq[10][5] = 0;
  dfkdot_dq[10][6] = 0;
  dfkdot_dq[10][7] = 0;
  dfkdot_dq[10][8] = 0;
  dfkdot_dq[11][0] = 0;
  dfkdot_dq[11][1] = 0;
  dfkdot_dq[11][2] = z[96];
  dfkdot_dq[11][3] = z[96];
  dfkdot_dq[11][4] = 0;
  dfkdot_dq[11][5] = 0;
  dfkdot_dq[11][6] = 0;
  dfkdot_dq[11][7] = 0;
  dfkdot_dq[11][8] = 0;
  dfkdot_dq[12][0] = 0;
  dfkdot_dq[12][1] = 0;
  dfkdot_dq[12][2] = -z[125];
  dfkdot_dq[12][3] = -z[125];
  dfkdot_dq[12][4] = 0;
  dfkdot_dq[12][5] = 0;
  dfkdot_dq[12][6] = 0;
  dfkdot_dq[12][7] = 0;
  dfkdot_dq[12][8] = 0;
  dfkdot_dq[13][0] = 0;
  dfkdot_dq[13][1] = 0;
  dfkdot_dq[13][2] = -z[126];
  dfkdot_dq[13][3] = -z[126];
  dfkdot_dq[13][4] = 0;
  dfkdot_dq[13][5] = 0;
  dfkdot_dq[13][6] = 0;
  dfkdot_dq[13][7] = 0;
  dfkdot_dq[13][8] = 0;
  dfkdot_dq[14][0] = 0;
  dfkdot_dq[14][1] = 0;
  dfkdot_dq[14][2] = z[128];
  dfkdot_dq[14][3] = z[128];
  dfkdot_dq[14][4] = z[101];
  dfkdot_dq[14][5] = 0;
  dfkdot_dq[14][6] = 0;
  dfkdot_dq[14][7] = 0;
  dfkdot_dq[14][8] = 0;
  dfkdot_dq[15][0] = 0;
  dfkdot_dq[15][1] = 0;
  dfkdot_dq[15][2] = z[131];
  dfkdot_dq[15][3] = z[131];
  dfkdot_dq[15][4] = z[133];
  dfkdot_dq[15][5] = 0;
  dfkdot_dq[15][6] = 0;
  dfkdot_dq[15][7] = 0;
  dfkdot_dq[15][8] = 0;
  dfkdot_dq[16][0] = 0;
  dfkdot_dq[16][1] = 0;
  dfkdot_dq[16][2] = z[100];
  dfkdot_dq[16][3] = z[100];
  dfkdot_dq[16][4] = z[103];
  dfkdot_dq[16][5] = 0;
  dfkdot_dq[16][6] = 0;
  dfkdot_dq[16][7] = 0;
  dfkdot_dq[16][8] = 0;
  dfkdot_dq[17][0] = 0;
  dfkdot_dq[17][1] = 0;
  dfkdot_dq[17][2] = z[101];
  dfkdot_dq[17][3] = z[101];
  dfkdot_dq[17][4] = z[135];
  dfkdot_dq[17][5] = 0;
  dfkdot_dq[17][6] = 0;
  dfkdot_dq[17][7] = 0;
  dfkdot_dq[17][8] = 0;
  dfkdot_dq[18][0] = 0;
  dfkdot_dq[18][1] = 0;
  dfkdot_dq[18][2] = z[136];
  dfkdot_dq[18][3] = z[136];
  dfkdot_dq[18][4] = -z[137];
  dfkdot_dq[18][5] = 0;
  dfkdot_dq[18][6] = 0;
  dfkdot_dq[18][7] = 0;
  dfkdot_dq[18][8] = 0;
  dfkdot_dq[19][0] = 0;
  dfkdot_dq[19][1] = 0;
  dfkdot_dq[19][2] = z[138];
  dfkdot_dq[19][3] = z[138];
  dfkdot_dq[19][4] = -z[139];
  dfkdot_dq[19][5] = 0;
  dfkdot_dq[19][6] = 0;
  dfkdot_dq[19][7] = 0;
  dfkdot_dq[19][8] = 0;
  dfkdot_dq[20][0] = 0;
  dfkdot_dq[20][1] = 0;
  dfkdot_dq[20][2] = z[142];
  dfkdot_dq[20][3] = z[142];
  dfkdot_dq[20][4] = z[144];
  dfkdot_dq[20][5] = z[107];
  dfkdot_dq[20][6] = 0;
  dfkdot_dq[20][7] = 0;
  dfkdot_dq[20][8] = 0;
  dfkdot_dq[21][0] = 0;
  dfkdot_dq[21][1] = 0;
  dfkdot_dq[21][2] = z[148];
  dfkdot_dq[21][3] = z[148];
  dfkdot_dq[21][4] = z[151];
  dfkdot_dq[21][5] = z[153];
  dfkdot_dq[21][6] = 0;
  dfkdot_dq[21][7] = 0;
  dfkdot_dq[21][8] = 0;
  dfkdot_dq[22][0] = 0;
  dfkdot_dq[22][1] = 0;
  dfkdot_dq[22][2] = z[106];
  dfkdot_dq[22][3] = z[106];
  dfkdot_dq[22][4] = z[155];
  dfkdot_dq[22][5] = z[109];
  dfkdot_dq[22][6] = 0;
  dfkdot_dq[22][7] = 0;
  dfkdot_dq[22][8] = 0;
  dfkdot_dq[23][0] = 0;
  dfkdot_dq[23][1] = 0;
  dfkdot_dq[23][2] = z[107];
  dfkdot_dq[23][3] = z[107];
  dfkdot_dq[23][4] = z[158];
  dfkdot_dq[23][5] = z[160];
  dfkdot_dq[23][6] = 0;
  dfkdot_dq[23][7] = 0;
  dfkdot_dq[23][8] = 0;
  dfkdot_dq[24][0] = 0;
  dfkdot_dq[24][1] = 0;
  dfkdot_dq[24][2] = 0;
  dfkdot_dq[24][3] = 0;
  dfkdot_dq[24][4] = 0;
  dfkdot_dq[24][5] = 0;
  dfkdot_dq[24][6] = 0;
  dfkdot_dq[24][7] = 0;
  dfkdot_dq[24][8] = 0;
  dfkdot_dq[25][0] = 0;
  dfkdot_dq[25][1] = 0;
  dfkdot_dq[25][2] = 0;
  dfkdot_dq[25][3] = 0;
  dfkdot_dq[25][4] = 0;
  dfkdot_dq[25][5] = 0;
  dfkdot_dq[25][6] = 0;
  dfkdot_dq[25][7] = 0;
  dfkdot_dq[25][8] = 0;
  dfkdot_dq[26][0] = 0;
  dfkdot_dq[26][1] = 0;
  dfkdot_dq[26][2] = z[111];
  dfkdot_dq[26][3] = 0;
  dfkdot_dq[26][4] = 0;
  dfkdot_dq[26][5] = 0;
  dfkdot_dq[26][6] = z[111];
  dfkdot_dq[26][7] = 0;
  dfkdot_dq[26][8] = 0;
  dfkdot_dq[27][0] = 0;
  dfkdot_dq[27][1] = 0;
  dfkdot_dq[27][2] = z[198];
  dfkdot_dq[27][3] = 0;
  dfkdot_dq[27][4] = 0;
  dfkdot_dq[27][5] = 0;
  dfkdot_dq[27][6] = z[198];
  dfkdot_dq[27][7] = 0;
  dfkdot_dq[27][8] = 0;
  dfkdot_dq[28][0] = 0;
  dfkdot_dq[28][1] = 0;
  dfkdot_dq[28][2] = z[110];
  dfkdot_dq[28][3] = 0;
  dfkdot_dq[28][4] = 0;
  dfkdot_dq[28][5] = 0;
  dfkdot_dq[28][6] = z[110];
  dfkdot_dq[28][7] = 0;
  dfkdot_dq[28][8] = 0;
  dfkdot_dq[29][0] = 0;
  dfkdot_dq[29][1] = 0;
  dfkdot_dq[29][2] = z[111];
  dfkdot_dq[29][3] = 0;
  dfkdot_dq[29][4] = 0;
  dfkdot_dq[29][5] = 0;
  dfkdot_dq[29][6] = z[111];
  dfkdot_dq[29][7] = 0;
  dfkdot_dq[29][8] = 0;
  dfkdot_dq[30][0] = 0;
  dfkdot_dq[30][1] = 0;
  dfkdot_dq[30][2] = -z[161];
  dfkdot_dq[30][3] = 0;
  dfkdot_dq[30][4] = 0;
  dfkdot_dq[30][5] = 0;
  dfkdot_dq[30][6] = -z[161];
  dfkdot_dq[30][7] = 0;
  dfkdot_dq[30][8] = 0;
  dfkdot_dq[31][0] = 0;
  dfkdot_dq[31][1] = 0;
  dfkdot_dq[31][2] = -z[162];
  dfkdot_dq[31][3] = 0;
  dfkdot_dq[31][4] = 0;
  dfkdot_dq[31][5] = 0;
  dfkdot_dq[31][6] = -z[162];
  dfkdot_dq[31][7] = 0;
  dfkdot_dq[31][8] = 0;
  dfkdot_dq[32][0] = 0;
  dfkdot_dq[32][1] = 0;
  dfkdot_dq[32][2] = z[164];
  dfkdot_dq[32][3] = 0;
  dfkdot_dq[32][4] = 0;
  dfkdot_dq[32][5] = 0;
  dfkdot_dq[32][6] = z[164];
  dfkdot_dq[32][7] = z[116];
  dfkdot_dq[32][8] = 0;
  dfkdot_dq[33][0] = 0;
  dfkdot_dq[33][1] = 0;
  dfkdot_dq[33][2] = z[167];
  dfkdot_dq[33][3] = 0;
  dfkdot_dq[33][4] = 0;
  dfkdot_dq[33][5] = 0;
  dfkdot_dq[33][6] = z[167];
  dfkdot_dq[33][7] = z[169];
  dfkdot_dq[33][8] = 0;
  dfkdot_dq[34][0] = 0;
  dfkdot_dq[34][1] = 0;
  dfkdot_dq[34][2] = z[115];
  dfkdot_dq[34][3] = 0;
  dfkdot_dq[34][4] = 0;
  dfkdot_dq[34][5] = 0;
  dfkdot_dq[34][6] = z[115];
  dfkdot_dq[34][7] = z[118];
  dfkdot_dq[34][8] = 0;
  dfkdot_dq[35][0] = 0;
  dfkdot_dq[35][1] = 0;
  dfkdot_dq[35][2] = z[116];
  dfkdot_dq[35][3] = 0;
  dfkdot_dq[35][4] = 0;
  dfkdot_dq[35][5] = 0;
  dfkdot_dq[35][6] = z[116];
  dfkdot_dq[35][7] = z[171];
  dfkdot_dq[35][8] = 0;
  dfkdot_dq[36][0] = 0;
  dfkdot_dq[36][1] = 0;
  dfkdot_dq[36][2] = z[172];
  dfkdot_dq[36][3] = 0;
  dfkdot_dq[36][4] = 0;
  dfkdot_dq[36][5] = 0;
  dfkdot_dq[36][6] = z[172];
  dfkdot_dq[36][7] = -z[173];
  dfkdot_dq[36][8] = 0;
  dfkdot_dq[37][0] = 0;
  dfkdot_dq[37][1] = 0;
  dfkdot_dq[37][2] = z[174];
  dfkdot_dq[37][3] = 0;
  dfkdot_dq[37][4] = 0;
  dfkdot_dq[37][5] = 0;
  dfkdot_dq[37][6] = z[174];
  dfkdot_dq[37][7] = -z[175];
  dfkdot_dq[37][8] = 0;
  dfkdot_dq[38][0] = 0;
  dfkdot_dq[38][1] = 0;
  dfkdot_dq[38][2] = z[178];
  dfkdot_dq[38][3] = 0;
  dfkdot_dq[38][4] = 0;
  dfkdot_dq[38][5] = 0;
  dfkdot_dq[38][6] = z[178];
  dfkdot_dq[38][7] = z[180];
  dfkdot_dq[38][8] = z[122];
  dfkdot_dq[39][0] = 0;
  dfkdot_dq[39][1] = 0;
  dfkdot_dq[39][2] = z[184];
  dfkdot_dq[39][3] = 0;
  dfkdot_dq[39][4] = 0;
  dfkdot_dq[39][5] = 0;
  dfkdot_dq[39][6] = z[184];
  dfkdot_dq[39][7] = z[187];
  dfkdot_dq[39][8] = z[189];
  dfkdot_dq[40][0] = 0;
  dfkdot_dq[40][1] = 0;
  dfkdot_dq[40][2] = z[121];
  dfkdot_dq[40][3] = 0;
  dfkdot_dq[40][4] = 0;
  dfkdot_dq[40][5] = 0;
  dfkdot_dq[40][6] = z[121];
  dfkdot_dq[40][7] = z[191];
  dfkdot_dq[40][8] = z[124];
  dfkdot_dq[41][0] = 0;
  dfkdot_dq[41][1] = 0;
  dfkdot_dq[41][2] = z[122];
  dfkdot_dq[41][3] = 0;
  dfkdot_dq[41][4] = 0;
  dfkdot_dq[41][5] = 0;
  dfkdot_dq[41][6] = z[122];
  dfkdot_dq[41][7] = z[194];
  dfkdot_dq[41][8] = z[196];
  Zero[0] = 0.01*z[275] - 0.01*z[300] - 0.01*z[288]*q9pp - 0.01*z[289]*q1pp - 
  0.01*z[290]*q2pp - 0.01*z[293]*q3pp - 0.01*z[294]*q7pp - 0.01*z[296]*q8pp - 
  0.01*z[297]*q6pp - 0.01*z[298]*q4pp - 0.01*z[299]*q5pp;
  Zero[1] = 0.01*z[276] - 0.01*z[309] - 0.01*z[290]*q1pp - 0.01*z[301]*q9pp - 
  0.01*z[302]*q2pp - 0.01*z[303]*q3pp - 0.01*z[304]*q7pp - 0.01*z[305]*q8pp - 
  0.01*z[306]*q6pp - 0.01*z[307]*q4pp - 0.01*z[308]*q5pp;
  Zero[2] = 0.01*z[277] - 0.01*z[320] - 0.01*z[293]*q1pp - 0.01*z[303]*q2pp - 
  0.01*z[311]*q3pp - 0.01*z[313]*q7pp - 0.01*z[315]*q8pp - 0.01*z[316]*q9pp - 
  0.01*z[317]*q4pp - 0.01*z[318]*q5pp - 0.01*z[319]*q6pp;
  Zero[3] = 0.01*z[278] - 0.01*z[321] - 0.01*z[298]*q1pp - 0.01*z[307]*q2pp - 
  0.01*z[317]*q3pp - 0.01*z[317]*q4pp - 0.01*z[318]*q5pp - 0.01*z[319]*q6pp;
  Zero[4] = 0.01*z[279] - 0.01*z[325] - 0.01*z[299]*q1pp - 0.01*z[308]*q2pp - 
  0.01*z[318]*q3pp - 0.01*z[318]*q4pp - 0.01*z[323]*q5pp - 0.01*z[324]*q6pp;
  Zero[5] = 0.01*z[284] - 0.01*z[327] - 0.01*z[326]*q6pp - 0.01*z[297]*q1pp - 
  0.01*z[306]*q2pp - 0.01*z[319]*q3pp - 0.01*z[319]*q4pp - 0.01*z[324]*q5pp;
  Zero[6] = 0.01*z[285] - 0.01*z[328] - 0.01*z[294]*q1pp - 0.01*z[304]*q2pp - 
  0.01*z[313]*q3pp - 0.01*z[313]*q7pp - 0.01*z[315]*q8pp - 0.01*z[316]*q9pp;
  Zero[7] = 0.01*z[286] - 0.01*z[331] - 0.01*z[296]*q1pp - 0.01*z[305]*q2pp - 
  0.01*z[315]*q3pp - 0.01*z[315]*q7pp - 0.01*z[329]*q8pp - 0.01*z[330]*q9pp;
  Zero[8] = 0.01*z[287] - 0.01*z[332] - 0.01*z[326]*q9pp - 0.01*z[288]*q1pp - 
  0.01*z[301]*q2pp - 0.01*z[316]*q3pp - 0.01*z[316]*q7pp - 0.01*z[330]*q8pp;
  dz_dq[0][0] = 0;
  dz_dq[0][1] = 0;
  dz_dq[0][2] = z[482];
  dz_dq[0][3] = z[483];
  dz_dq[0][4] = z[484];
  dz_dq[0][5] = z[485];
  dz_dq[0][6] = z[486];
  dz_dq[0][7] = z[487];
  dz_dq[0][8] = z[488];
  dz_dq[1][0] = 0;
  dz_dq[1][1] = 0;
  dz_dq[1][2] = z[489];
  dz_dq[1][3] = z[490];
  dz_dq[1][4] = z[491];
  dz_dq[1][5] = z[492];
  dz_dq[1][6] = z[493];
  dz_dq[1][7] = z[494];
  dz_dq[1][8] = z[495];
  dz_dq[2][0] = z[496];
  dz_dq[2][1] = z[497];
  dz_dq[2][2] = z[498];
  dz_dq[2][3] = z[499];
  dz_dq[2][4] = z[500];
  dz_dq[2][5] = z[501];
  dz_dq[2][6] = z[502];
  dz_dq[2][7] = z[503];
  dz_dq[2][8] = z[504];
  dz_dq[3][0] = -0.01*z[255];
  dz_dq[3][1] = 0.01*z[254];
  dz_dq[3][2] = z[499];
  dz_dq[3][3] = z[499];
  dz_dq[3][4] = z[500];
  dz_dq[3][5] = z[501];
  dz_dq[3][6] = 0;
  dz_dq[3][7] = 0;
  dz_dq[3][8] = 0;
  dz_dq[4][0] = -0.01*z[255];
  dz_dq[4][1] = 0.01*z[254];
  dz_dq[4][2] = z[505];
  dz_dq[4][3] = z[505];
  dz_dq[4][4] = z[506];
  dz_dq[4][5] = z[507];
  dz_dq[4][6] = 0;
  dz_dq[4][7] = 0;
  dz_dq[4][8] = 0;
  dz_dq[5][0] = -0.01*z[255];
  dz_dq[5][1] = 0.01*z[254];
  dz_dq[5][2] = z[508];
  dz_dq[5][3] = z[508];
  dz_dq[5][4] = z[509];
  dz_dq[5][5] = z[510];
  dz_dq[5][6] = 0;
  dz_dq[5][7] = 0;
  dz_dq[5][8] = 0;
  dz_dq[6][0] = -0.01*z[263];
  dz_dq[6][1] = 0.01*z[262];
  dz_dq[6][2] = z[502];
  dz_dq[6][3] = 0;
  dz_dq[6][4] = 0;
  dz_dq[6][5] = 0;
  dz_dq[6][6] = z[502];
  dz_dq[6][7] = z[503];
  dz_dq[6][8] = z[504];
  dz_dq[7][0] = -0.01*z[263];
  dz_dq[7][1] = 0.01*z[262];
  dz_dq[7][2] = z[511];
  dz_dq[7][3] = 0;
  dz_dq[7][4] = 0;
  dz_dq[7][5] = 0;
  dz_dq[7][6] = z[511];
  dz_dq[7][7] = z[512];
  dz_dq[7][8] = z[513];
  dz_dq[8][0] = -0.01*z[263];
  dz_dq[8][1] = 0.01*z[262];
  dz_dq[8][2] = z[514];
  dz_dq[8][3] = 0;
  dz_dq[8][4] = 0;
  dz_dq[8][5] = 0;
  dz_dq[8][6] = z[514];
  dz_dq[8][7] = z[515];
  dz_dq[8][8] = z[516];
  dz_dqd[0][0] = 0.01*z[520];
  dz_dqd[0][1] = 0.01*z[524];
  dz_dqd[0][2] = z[598];
  dz_dqd[0][3] = -0.01*z[548];
  dz_dqd[0][4] = -0.01*z[553];
  dz_dqd[0][5] = 0.01*z[556];
  dz_dqd[0][6] = -0.01*z[557];
  dz_dqd[0][7] = -0.01*z[562];
  dz_dqd[0][8] = 0.01*z[565];
  dz_dqd[1][0] = 0.01*z[566];
  dz_dqd[1][1] = 0.01*z[567];
  dz_dqd[1][2] = z[599];
  dz_dqd[1][3] = -0.01*z[570];
  dz_dqd[1][4] = -0.01*z[571];
  dz_dqd[1][5] = 0.01*z[572];
  dz_dqd[1][6] = -0.01*z[573];
  dz_dqd[1][7] = -0.01*z[574];
  dz_dqd[1][8] = 0.01*z[575];
  dz_dqd[2][0] = -0.01*z[576];
  dz_dqd[2][1] = -0.01*z[577];
  dz_dqd[2][2] = z[600];
  dz_dqd[2][3] = -0.01*z[580];
  dz_dqd[2][4] = -0.01*z[581];
  dz_dqd[2][5] = 0.01*z[582];
  dz_dqd[2][6] = -0.01*z[583];
  dz_dqd[2][7] = -0.01*z[584];
  dz_dqd[2][8] = 0.01*z[585];
  dz_dqd[3][0] = 0;
  dz_dqd[3][1] = 0;
  dz_dqd[3][2] = -0.01*z[580];
  dz_dqd[3][3] = -0.01*z[580];
  dz_dqd[3][4] = -0.01*z[581];
  dz_dqd[3][5] = 0.01*z[582];
  dz_dqd[3][6] = 0;
  dz_dqd[3][7] = 0;
  dz_dqd[3][8] = 0;
  dz_dqd[4][0] = 0;
  dz_dqd[4][1] = 0;
  dz_dqd[4][2] = -0.01*z[586];
  dz_dqd[4][3] = -0.01*z[586];
  dz_dqd[4][4] = -0.01*z[587];
  dz_dqd[4][5] = 0.01*z[588];
  dz_dqd[4][6] = 0;
  dz_dqd[4][7] = 0;
  dz_dqd[4][8] = 0;
  dz_dqd[5][0] = 0;
  dz_dqd[5][1] = 0;
  dz_dqd[5][2] = -0.01*z[589];
  dz_dqd[5][3] = -0.01*z[589];
  dz_dqd[5][4] = -0.01*z[590];
  dz_dqd[5][5] = 0.01*z[591];
  dz_dqd[5][6] = 0;
  dz_dqd[5][7] = 0;
  dz_dqd[5][8] = 0;
  dz_dqd[6][0] = 0;
  dz_dqd[6][1] = 0;
  dz_dqd[6][2] = -0.01*z[583];
  dz_dqd[6][3] = 0;
  dz_dqd[6][4] = 0;
  dz_dqd[6][5] = 0;
  dz_dqd[6][6] = -0.01*z[583];
  dz_dqd[6][7] = -0.01*z[584];
  dz_dqd[6][8] = 0.01*z[585];
  dz_dqd[7][0] = 0;
  dz_dqd[7][1] = 0;
  dz_dqd[7][2] = -0.01*z[592];
  dz_dqd[7][3] = 0;
  dz_dqd[7][4] = 0;
  dz_dqd[7][5] = 0;
  dz_dqd[7][6] = -0.01*z[592];
  dz_dqd[7][7] = -0.01*z[593];
  dz_dqd[7][8] = 0.01*z[594];
  dz_dqd[8][0] = 0;
  dz_dqd[8][1] = 0;
  dz_dqd[8][2] = -0.01*z[595];
  dz_dqd[8][3] = 0;
  dz_dqd[8][4] = 0;
  dz_dqd[8][5] = 0;
  dz_dqd[8][6] = -0.01*z[595];
  dz_dqd[8][7] = -0.01*z[596];
  dz_dqd[8][8] = 0.01*z[597];
  dz_dqdd[0][0] = -0.01*z[289];
  dz_dqdd[0][1] = -0.01*z[290];
  dz_dqdd[0][2] = -0.01*z[293];
  dz_dqdd[0][3] = -0.01*z[298];
  dz_dqdd[0][4] = -0.01*z[299];
  dz_dqdd[0][5] = -0.01*z[297];
  dz_dqdd[0][6] = -0.01*z[294];
  dz_dqdd[0][7] = -0.01*z[296];
  dz_dqdd[0][8] = -0.01*z[288];
  dz_dqdd[1][0] = -0.01*z[290];
  dz_dqdd[1][1] = -0.01*z[302];
  dz_dqdd[1][2] = -0.01*z[303];
  dz_dqdd[1][3] = -0.01*z[307];
  dz_dqdd[1][4] = -0.01*z[308];
  dz_dqdd[1][5] = -0.01*z[306];
  dz_dqdd[1][6] = -0.01*z[304];
  dz_dqdd[1][7] = -0.01*z[305];
  dz_dqdd[1][8] = -0.01*z[301];
  dz_dqdd[2][0] = -0.01*z[293];
  dz_dqdd[2][1] = -0.01*z[303];
  dz_dqdd[2][2] = -0.01*z[311];
  dz_dqdd[2][3] = -0.01*z[317];
  dz_dqdd[2][4] = -0.01*z[318];
  dz_dqdd[2][5] = -0.01*z[319];
  dz_dqdd[2][6] = -0.01*z[313];
  dz_dqdd[2][7] = -0.01*z[315];
  dz_dqdd[2][8] = -0.01*z[316];
  dz_dqdd[3][0] = -0.01*z[298];
  dz_dqdd[3][1] = -0.01*z[307];
  dz_dqdd[3][2] = -0.01*z[317];
  dz_dqdd[3][3] = -0.01*z[317];
  dz_dqdd[3][4] = -0.01*z[318];
  dz_dqdd[3][5] = -0.01*z[319];
  dz_dqdd[3][6] = 0;
  dz_dqdd[3][7] = 0;
  dz_dqdd[3][8] = 0;
  dz_dqdd[4][0] = -0.01*z[299];
  dz_dqdd[4][1] = -0.01*z[308];
  dz_dqdd[4][2] = -0.01*z[318];
  dz_dqdd[4][3] = -0.01*z[318];
  dz_dqdd[4][4] = -0.01*z[323];
  dz_dqdd[4][5] = -0.01*z[324];
  dz_dqdd[4][6] = 0;
  dz_dqdd[4][7] = 0;
  dz_dqdd[4][8] = 0;
  dz_dqdd[5][0] = -0.01*z[297];
  dz_dqdd[5][1] = -0.01*z[306];
  dz_dqdd[5][2] = -0.01*z[319];
  dz_dqdd[5][3] = -0.01*z[319];
  dz_dqdd[5][4] = -0.01*z[324];
  dz_dqdd[5][5] = -0.01*z[326];
  dz_dqdd[5][6] = 0;
  dz_dqdd[5][7] = 0;
  dz_dqdd[5][8] = 0;
  dz_dqdd[6][0] = -0.01*z[294];
  dz_dqdd[6][1] = -0.01*z[304];
  dz_dqdd[6][2] = -0.01*z[313];
  dz_dqdd[6][3] = 0;
  dz_dqdd[6][4] = 0;
  dz_dqdd[6][5] = 0;
  dz_dqdd[6][6] = -0.01*z[313];
  dz_dqdd[6][7] = -0.01*z[315];
  dz_dqdd[6][8] = -0.01*z[316];
  dz_dqdd[7][0] = -0.01*z[296];
  dz_dqdd[7][1] = -0.01*z[305];
  dz_dqdd[7][2] = -0.01*z[315];
  dz_dqdd[7][3] = 0;
  dz_dqdd[7][4] = 0;
  dz_dqdd[7][5] = 0;
  dz_dqdd[7][6] = -0.01*z[315];
  dz_dqdd[7][7] = -0.01*z[329];
  dz_dqdd[7][8] = -0.01*z[330];
  dz_dqdd[8][0] = -0.01*z[288];
  dz_dqdd[8][1] = -0.01*z[301];
  dz_dqdd[8][2] = -0.01*z[316];
  dz_dqdd[8][3] = 0;
  dz_dqdd[8][4] = 0;
  dz_dqdd[8][5] = 0;
  dz_dqdd[8][6] = -0.01*z[316];
  dz_dqdd[8][7] = -0.01*z[330];
  dz_dqdd[8][8] = -0.01*z[326];
  dz_dmom[0][0] = 0;
  dz_dmom[0][1] = 0;
  dz_dmom[0][2] = 0;
  dz_dmom[0][3] = 0;
  dz_dmom[0][4] = 0;
  dz_dmom[0][5] = 0;
  dz_dmom[1][0] = 0;
  dz_dmom[1][1] = 0;
  dz_dmom[1][2] = 0;
  dz_dmom[1][3] = 0;
  dz_dmom[1][4] = 0;
  dz_dmom[1][5] = 0;
  dz_dmom[2][0] = 0;
  dz_dmom[2][1] = 0;
  dz_dmom[2][2] = 0;
  dz_dmom[2][3] = 0;
  dz_dmom[2][4] = 0;
  dz_dmom[2][5] = 0;
  dz_dmom[3][0] = 0.01;
  dz_dmom[3][1] = 0;
  dz_dmom[3][2] = 0;
  dz_dmom[3][3] = 0;
  dz_dmom[3][4] = 0;
  dz_dmom[3][5] = 0;
  dz_dmom[4][0] = 0;
  dz_dmom[4][1] = 0.01;
  dz_dmom[4][2] = 0;
  dz_dmom[4][3] = 0;
  dz_dmom[4][4] = 0;
  dz_dmom[4][5] = 0;
  dz_dmom[5][0] = 0;
  dz_dmom[5][1] = 0;
  dz_dmom[5][2] = 0.01;
  dz_dmom[5][3] = 0;
  dz_dmom[5][4] = 0;
  dz_dmom[5][5] = 0;
  dz_dmom[6][0] = 0;
  dz_dmom[6][1] = 0;
  dz_dmom[6][2] = 0;
  dz_dmom[6][3] = 0.01;
  dz_dmom[6][4] = 0;
  dz_dmom[6][5] = 0;
  dz_dmom[7][0] = 0;
  dz_dmom[7][1] = 0;
  dz_dmom[7][2] = 0;
  dz_dmom[7][3] = 0;
  dz_dmom[7][4] = 0.01;
  dz_dmom[7][5] = 0;
  dz_dmom[8][0] = 0;
  dz_dmom[8][1] = 0;
  dz_dmom[8][2] = 0;
  dz_dmom[8][3] = 0;
  dz_dmom[8][4] = 0;
  dz_dmom[8][5] = 0.01;
  dz_dgrf[0][0] = 0.01*z[615];
  dz_dgrf[0][1] = 0.01*z[601];
  dz_dgrf[0][2] = 0;
  dz_dgrf[0][3] = 0.01*z[616];
  dz_dgrf[0][4] = 0.01*z[602];
  dz_dgrf[0][5] = 0;
  dz_dgrf[1][0] = 0.01*z[601];
  dz_dgrf[1][1] = 0.01*z[617];
  dz_dgrf[1][2] = 0;
  dz_dgrf[1][3] = 0.01*z[602];
  dz_dgrf[1][4] = 0.01*z[618];
  dz_dgrf[1][5] = 0;
  dz_dgrf[2][0] = -0.01*z[603];
  dz_dgrf[2][1] = -0.01*z[604];
  dz_dgrf[2][2] = 0.01*par->bodyweight;
  dz_dgrf[2][3] = -0.01*z[605];
  dz_dgrf[2][4] = -0.01*z[606];
  dz_dgrf[2][5] = 0.01*par->bodyweight;
  dz_dgrf[3][0] = -0.01*z[603];
  dz_dgrf[3][1] = -0.01*z[604];
  dz_dgrf[3][2] = 0.01*par->bodyweight;
  dz_dgrf[3][3] = 0;
  dz_dgrf[3][4] = 0;
  dz_dgrf[3][5] = 0;
  dz_dgrf[4][0] = -0.01*z[607];
  dz_dgrf[4][1] = -0.01*z[608];
  dz_dgrf[4][2] = 0.01*par->bodyweight;
  dz_dgrf[4][3] = 0;
  dz_dgrf[4][4] = 0;
  dz_dgrf[4][5] = 0;
  dz_dgrf[5][0] = 0.01*z[609];
  dz_dgrf[5][1] = -0.01*z[610];
  dz_dgrf[5][2] = 0.01*par->bodyweight;
  dz_dgrf[5][3] = 0;
  dz_dgrf[5][4] = 0;
  dz_dgrf[5][5] = 0;
  dz_dgrf[6][0] = 0;
  dz_dgrf[6][1] = 0;
  dz_dgrf[6][2] = 0;
  dz_dgrf[6][3] = -0.01*z[605];
  dz_dgrf[6][4] = -0.01*z[606];
  dz_dgrf[6][5] = 0.01*par->bodyweight;
  dz_dgrf[7][0] = 0;
  dz_dgrf[7][1] = 0;
  dz_dgrf[7][2] = 0;
  dz_dgrf[7][3] = -0.01*z[611];
  dz_dgrf[7][4] = -0.01*z[612];
  dz_dgrf[7][5] = 0.01*par->bodyweight;
  dz_dgrf[8][0] = 0;
  dz_dgrf[8][1] = 0;
  dz_dgrf[8][2] = 0;
  dz_dgrf[8][3] = 0.01*z[613];
  dz_dgrf[8][4] = -0.01*z[614];
  dz_dgrf[8][5] = 0.01*par->bodyweight;

}
