%======================================================================
%> @file saveLaTeXDocument.m
%> @brief Function to save a text body within a LaTeX document
%>
%> @author Marlies Nitschke
%> @date September, 2018
%======================================================================

%======================================================================
%> @brief Function to save a text body within a LaTeX document
%>
%> @details
%> This function generates a standard LaTeX document and adds the textBody
%> after the tiltle in the document body. It does not ensure that all
%> required packages are included. Finally, it saves the document using 
%> fileName. 
%>
%> @param textBody  String: Text which will be insert into the document
%>                  body. This has to be already in LaTeX format.
%> @param fileName  String: Name to save the document as <fileName>.tex
%> @param docTitle  String: Title of the document
%======================================================================
function texStringDocument = saveLaTeXDocument(textBody, fileName, docTitle)

% Create string containing all the packages
texStringPackages = [...
    '%--------------------', newline,...
    '% Packages', newline,...
    '% -------------------', newline,...
    '\documentclass[11pt,a4paper]{article}', newline,...
    '\usepackage[top=2.5cm, bottom=2cm, left=2.5cm, right=2.5cm]{geometry}', newline, ...
    '\usepackage[utf8]{inputenc}', newline,...
    '\usepackage[T1]{fontenc}', newline,...
    '\usepackage{mathptmx} % Use Times Font', newline,...
    newline, ...
    '\usepackage{booktabs} % toprule and midrule in tables', newline, ...
    '\usepackage{float} % package for enforce placement of floats', newline, ...
    '\usepackage{pgfplots}', newline,...
    '\pgfplotsset{compat=newest}', newline,...
    '\usetikzlibrary{plotmarks}', newline,...
    '\usetikzlibrary{arrows.meta}', newline,...
    '\usepgfplotslibrary{patchplots}', newline, ...
    newline, ...
    '\usepackage{amsmath}', newline,...
    '\usepackage{graphicx} % Required for including pictures', newline, ...
    '\usepackage{hyperref}', newline, ...
    '\usepackage{standalone}', newline, ...
    '\hypersetup{', newline, ...
    '    colorlinks=true,', newline, ...
    '    allcolors=black, ', newline, ...
    '    bookmarksnumbered=true,', newline, ...
    '    pdfstartview=Fit', newline, ...
    '}', newline, ...
    '\usepackage{enumitem} % Includes lists', newline, ...
    newline, ...
    '% Reduce space between items', newline, ...
    '\let\tempone\itemize', newline, ...
    '\let\temptwo\enditemize', newline, ...
    '\renewenvironment{itemize}{\tempone\addtolength{\itemsep}{0.3\baselineskip}}{\temptwo}', newline];


% Create title

texStringTitle = sprintf('\\title{%s}\n ', docTitle);

% Create document body
texStringBody = [...
    '%--------------------', newline,...
    '% Begin document', newline,...
    '% -------------------', newline,...
    '\begin{document}', newline, ...
    '\maketitle', newline, ...
    newline, textBody, newline, ....
    '\end{document}', newline];


% Combine the parts of the document
texStringDocument = [texStringPackages, texStringTitle, texStringBody];

% Save it
fileID = fopen([fileName '.tex'],'w');
fprintf(fileID,'%s',texStringDocument);
fclose(fileID);

end